// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol BackupForGKEStub: Sendable {
    func createBackupPlan(
      request: CreateBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBackupPlans(
      request: ListBackupPlansRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupPlansResponse

    func getBackupPlan(
      request: GetBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.BackupPlan

    func updateBackupPlan(
      request: UpdateBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBackupPlan(
      request: DeleteBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBackupChannel(
      request: CreateBackupChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBackupChannels(
      request: ListBackupChannelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupChannelsResponse

    func getBackupChannel(
      request: GetBackupChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.BackupChannel

    func updateBackupChannel(
      request: UpdateBackupChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBackupChannel(
      request: DeleteBackupChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBackupPlanBindings(
      request: ListBackupPlanBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupPlanBindingsResponse

    func getBackupPlanBinding(
      request: GetBackupPlanBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.BackupPlanBinding

    func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupsResponse

    func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.Backup

    func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listVolumeBackups(
      request: ListVolumeBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListVolumeBackupsResponse

    func getVolumeBackup(
      request: GetVolumeBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.VolumeBackup

    func createRestorePlan(
      request: CreateRestorePlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRestorePlans(
      request: ListRestorePlansRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestorePlansResponse

    func getRestorePlan(
      request: GetRestorePlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.RestorePlan

    func updateRestorePlan(
      request: UpdateRestorePlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRestorePlan(
      request: DeleteRestorePlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createRestoreChannel(
      request: CreateRestoreChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRestoreChannels(
      request: ListRestoreChannelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestoreChannelsResponse

    func getRestoreChannel(
      request: GetRestoreChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.RestoreChannel

    func updateRestoreChannel(
      request: UpdateRestoreChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRestoreChannel(
      request: DeleteRestoreChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRestorePlanBindings(
      request: ListRestorePlanBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestorePlanBindingsResponse

    func getRestorePlanBinding(
      request: GetRestorePlanBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.RestorePlanBinding

    func createRestore(
      request: CreateRestoreRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRestores(
      request: ListRestoresRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestoresResponse

    func getRestore(
      request: GetRestoreRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.Restore

    func updateRestore(
      request: UpdateRestoreRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRestore(
      request: DeleteRestoreRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listVolumeRestores(
      request: ListVolumeRestoresRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListVolumeRestoresResponse

    func getVolumeRestore(
      request: GetVolumeRestoreRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.VolumeRestore

    func getBackupIndexDownloadUrl(
      request: GetBackupIndexDownloadUrlRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.GetBackupIndexDownloadUrlResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
