// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A BackupChannel imposes constraints on where clusters can be backed up.
/// The BackupChannel should be in the same project and region
/// as the cluster being backed up.
/// The backup can be created only in destination_project.
public struct BackupChannel: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The fully qualified name of the BackupChannel.
  /// `projects/*/locations/*/backupChannels/*`
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The project where Backups are allowed to be stored.
  /// The format is `projects/{projectId}` or `projects/{projectNumber}`.
  public var destinationProject: Swift.String = Swift.String()

  /// Output only. Server generated global unique identifier of
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) format.
  public var uid: Swift.String = Swift.String()

  /// Output only. The timestamp when this BackupChannel resource was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when this BackupChannel resource was last
  /// updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. User specified descriptive string for this BackupChannel.
  public var description: Swift.String = Swift.String()

  /// Output only. `etag` is used for optimistic concurrency control as a way to
  /// help prevent simultaneous updates of a BackupChannel from overwriting each
  /// other. It is strongly suggested that systems make use of the 'etag' in the
  /// read-modify-write cycle to perform BackupChannel updates in order to
  /// avoid race conditions: An `etag` is returned in the response to
  /// `GetBackupChannel`, and systems are expected to put that etag in the
  /// request to `UpdateBackupChannel` or `DeleteBackupChannel` to
  /// ensure that their change will be applied to the same version of the
  /// resource.
  public var etag: Swift.String = Swift.String()

  /// Output only. The project_id where Backups are allowed to be stored.
  /// Example Project ID: "my-project-id".
  /// This will be an OUTPUT_ONLY field to return the project_id of the
  /// destination project.
  public var destinationProjectId: Swift.String = Swift.String()

  /// Initialize a new instance of `BackupChannel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupChannel().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.BackupChannel"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
