// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines the configuration and scheduling for a "line" of Backups.
public struct BackupPlan: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full name of the BackupPlan resource.
  /// Format: `projects/*/locations/*/backupPlans/*`
  public var name: Swift.String = Swift.String()

  /// Output only. Server generated global unique identifier of
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) format.
  public var uid: Swift.String = Swift.String()

  /// Output only. The timestamp when this BackupPlan resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when this BackupPlan resource was last
  /// updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. User specified descriptive string for this BackupPlan.
  public var description: Swift.String = Swift.String()

  /// Required. Immutable. The source cluster from which Backups will be created
  /// via this BackupPlan. Valid formats:
  ///
  /// - `projects/*/locations/*/clusters/*`
  /// - `projects/*/zones/*/clusters/*`
  public var cluster: Swift.String = Swift.String()

  /// Optional. RetentionPolicy governs lifecycle of Backups created under this
  /// plan.
  public var retentionPolicy: BackupPlan.RetentionPolicy? = nil

  /// Optional. A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Defines a schedule for automatic Backup creation via this
  /// BackupPlan.
  public var backupSchedule: BackupPlan.Schedule? = nil

  /// Output only. `etag` is used for optimistic concurrency control as a way to
  /// help prevent simultaneous updates of a backup plan from overwriting each
  /// other. It is strongly suggested that systems make use of the 'etag' in the
  /// read-modify-write cycle to perform BackupPlan updates in order to avoid
  /// race conditions: An `etag` is returned in the response to `GetBackupPlan`,
  /// and systems are expected to put that etag in the request to
  /// `UpdateBackupPlan` or `DeleteBackupPlan` to ensure that their change
  /// will be applied to the same version of the resource.
  public var etag: Swift.String = Swift.String()

  /// Optional. This flag indicates whether this BackupPlan has been deactivated.
  /// Setting this field to True locks the BackupPlan such that no further
  /// updates will be allowed (except deletes), including the deactivated field
  /// itself. It also prevents any new Backups from being created via this
  /// BackupPlan (including scheduled Backups).
  ///
  /// Default: False
  public var deactivated: Swift.Bool = Swift.Bool()

  /// Optional. Defines the configuration of Backups created via this BackupPlan.
  public var backupConfig: BackupPlan.BackupConfig? = nil

  /// Output only. The number of Kubernetes Pods backed up in the
  /// last successful Backup created via this BackupPlan.
  public var protectedPodCount: Swift.Int32 = Swift.Int32()

  /// Output only. State of the BackupPlan. This State field reflects the
  /// various stages a BackupPlan can be in
  /// during the Create operation. It will be set to "DEACTIVATED"
  /// if the BackupPlan is deactivated on an Update
  public var state: BackupPlan.State = BackupPlan.State()

  /// Output only. Human-readable description of why BackupPlan is in the current
  /// `state`. This field is only meant for human readability and should not be
  /// used programmatically as this field is not guaranteed to be consistent.
  public var stateReason: Swift.String = Swift.String()

  /// Output only. A number that represents the current risk level of this
  /// BackupPlan from RPO perspective with 1 being no risk and 5 being highest
  /// risk.
  public var rpoRiskLevel: Swift.Int32 = Swift.Int32()

  /// Output only. Human-readable description of why the BackupPlan is in the
  /// current rpo_risk_level and action items if any.
  public var rpoRiskReason: Swift.String = Swift.String()

  /// Output only. The fully qualified name of the BackupChannel to be used to
  /// create a backup. This field is set only if the cluster being backed up is
  /// in a different project.
  /// `projects/*/locations/*/backupChannels/*`
  public var backupChannel: Swift.String = Swift.String()

  /// Output only. Completion time of the last successful Backup. This is sourced
  /// from a successful Backup's complete_time field. This field is added to
  /// maintain consistency with BackupPlanBinding to display last successful
  /// backup time.
  public var lastSuccessfulBackupTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupPlan`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupPlan().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let description = CodingKeys(stringValue: "description")
    static let cluster = CodingKeys(stringValue: "cluster")
    static let retentionPolicy = CodingKeys(stringValue: "retentionPolicy")
    static let labels = CodingKeys(stringValue: "labels")
    static let backupSchedule = CodingKeys(stringValue: "backupSchedule")
    static let etag = CodingKeys(stringValue: "etag")
    static let deactivated = CodingKeys(stringValue: "deactivated")
    static let backupConfig = CodingKeys(stringValue: "backupConfig")
    static let protectedPodCount = CodingKeys(stringValue: "protectedPodCount")
    static let state = CodingKeys(stringValue: "state")
    static let stateReason = CodingKeys(stringValue: "stateReason")
    static let rpoRiskLevel = CodingKeys(stringValue: "rpoRiskLevel")
    static let rpoRiskReason = CodingKeys(stringValue: "rpoRiskReason")
    static let backupChannel = CodingKeys(stringValue: "backupChannel")
    static let lastSuccessfulBackupTime = CodingKeys(stringValue: "lastSuccessfulBackupTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "createTime",
      "updateTime",
      "description",
      "cluster",
      "retentionPolicy",
      "labels",
      "backupSchedule",
      "etag",
      "deactivated",
      "backupConfig",
      "protectedPodCount",
      "state",
      "stateReason",
      "rpoRiskLevel",
      "rpoRiskReason",
      "backupChannel",
      "lastSuccessfulBackupTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
      self.cluster = value
    }
    self.retentionPolicy = try container.decodeIfPresent(
      BackupPlan.RetentionPolicy.self, forKey: .retentionPolicy)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.backupSchedule = try container.decodeIfPresent(
      BackupPlan.Schedule.self, forKey: .backupSchedule)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deactivated) {
      self.deactivated = value
    }
    self.backupConfig = try container.decodeIfPresent(
      BackupPlan.BackupConfig.self, forKey: .backupConfig)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .protectedPodCount) {
      self.protectedPodCount = value
    }
    if let value = try container.decodeIfPresent(BackupPlan.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateReason) {
      self.stateReason = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .rpoRiskLevel) {
      self.rpoRiskLevel = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rpoRiskReason) {
      self.rpoRiskReason = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupChannel) {
      self.backupChannel = value
    }
    self.lastSuccessfulBackupTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastSuccessfulBackupTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.cluster, forKey: .cluster)
    try container.encodeIfPresent(self.retentionPolicy, forKey: .retentionPolicy)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.backupSchedule, forKey: .backupSchedule)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.deactivated, forKey: .deactivated)
    try container.encodeIfPresent(self.backupConfig, forKey: .backupConfig)
    try container.encode(self.protectedPodCount, forKey: .protectedPodCount)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateReason, forKey: .stateReason)
    try container.encode(self.rpoRiskLevel, forKey: .rpoRiskLevel)
    try container.encode(self.rpoRiskReason, forKey: .rpoRiskReason)
    try container.encode(self.backupChannel, forKey: .backupChannel)
    try container.encodeIfPresent(self.lastSuccessfulBackupTime, forKey: .lastSuccessfulBackupTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// RetentionPolicy defines a Backup retention policy for a BackupPlan.
  public struct RetentionPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Minimum age for Backups created via this BackupPlan (in days).
    /// This field MUST be an integer value between 0-90 (inclusive).
    /// A Backup created under this BackupPlan will NOT be deletable until it
    /// reaches Backup's (create_time + backup_delete_lock_days).
    /// Updating this field of a BackupPlan does NOT affect existing Backups
    /// under it. Backups created AFTER a successful update will inherit
    /// the new value.
    ///
    /// Default: 0 (no delete blocking)
    public var backupDeleteLockDays: Swift.Int32 = Swift.Int32()

    /// Optional. The default maximum age of a Backup created via this
    /// BackupPlan. This field MUST be an integer value >= 0 and <= 365. If
    /// specified, a Backup created under this BackupPlan will be automatically
    /// deleted after its age reaches (create_time + backup_retain_days). If not
    /// specified, Backups created under this BackupPlan will NOT be subject to
    /// automatic deletion. Updating this field does NOT affect existing Backups
    /// under it. Backups created AFTER a successful update will automatically
    /// pick up the new value. NOTE: backup_retain_days must be >=
    /// [backup_delete_lock_days][google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_delete_lock_days].
    /// If
    /// [cron_schedule][google.cloud.gkebackup.v1.BackupPlan.Schedule.cron_schedule]
    /// is defined, then this must be
    /// <= 360 * the creation interval. If
    /// [rpo_config][google.cloud.gkebackup.v1.BackupPlan.Schedule.rpo_config] is
    /// defined, then this must be
    /// <= 360 * [target_rpo_minutes][Schedule.rpo_config.target_rpo_minutes] /
    /// (1440minutes/day).
    ///
    /// Default: 0 (no automatic deletion)
    ///
    /// [google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_delete_lock_days]: <doc:BackupPlan/RetentionPolicy/backupDeleteLockDays>
    /// [google.cloud.gkebackup.v1.BackupPlan.Schedule.cron_schedule]: <doc:BackupPlan/Schedule/cronSchedule>
    /// [google.cloud.gkebackup.v1.BackupPlan.Schedule.rpo_config]: <doc:BackupPlan/Schedule/rpoConfig>
    public var backupRetainDays: Swift.Int32 = Swift.Int32()

    /// Optional. This flag denotes whether the retention policy of this
    /// BackupPlan is locked.  If set to True, no further update is allowed on
    /// this policy, including the `locked` field itself.
    ///
    /// Default: False
    public var locked: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RetentionPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RetentionPolicy().with { $0.backupDeleteLockDays = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let backupDeleteLockDays = CodingKeys(stringValue: "backupDeleteLockDays")
      static let backupRetainDays = CodingKeys(stringValue: "backupRetainDays")
      static let locked = CodingKeys(stringValue: "locked")

      static let _knownKeys: Set<Swift.String> = [
        "backupDeleteLockDays",
        "backupRetainDays",
        "locked",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .backupDeleteLockDays)
      {
        self.backupDeleteLockDays = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .backupRetainDays) {
        self.backupRetainDays = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .locked) {
        self.locked = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.backupDeleteLockDays, forKey: .backupDeleteLockDays)
      try container.encode(self.backupRetainDays, forKey: .backupRetainDays)
      try container.encode(self.locked, forKey: .locked)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines scheduling parameters for automatically creating Backups
  /// via this BackupPlan.
  public struct Schedule: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. A standard [cron](https://wikipedia.com/wiki/cron) string that
    /// defines a repeating schedule for creating Backups via this BackupPlan.
    /// This is mutually exclusive with the
    /// [rpo_config][google.cloud.gkebackup.v1.BackupPlan.Schedule.rpo_config]
    /// field since at most one schedule can be defined for a BackupPlan. If this
    /// is defined, then
    /// [backup_retain_days][google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_retain_days]
    /// must also be defined.
    ///
    /// Default (empty): no automatic backup creation will occur.
    ///
    /// [google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_retain_days]: <doc:BackupPlan/RetentionPolicy/backupRetainDays>
    /// [google.cloud.gkebackup.v1.BackupPlan.Schedule.rpo_config]: <doc:BackupPlan/Schedule/rpoConfig>
    public var cronSchedule: Swift.String = Swift.String()

    /// Optional. This flag denotes whether automatic Backup creation is paused
    /// for this BackupPlan.
    ///
    /// Default: False
    public var paused: Swift.Bool = Swift.Bool()

    /// Optional. Defines the RPO schedule configuration for this BackupPlan.
    /// This is mutually exclusive with the
    /// [cron_schedule][google.cloud.gkebackup.v1.BackupPlan.Schedule.cron_schedule]
    /// field since at most one schedule can be defined for a BackupPLan. If this
    /// is defined, then
    /// [backup_retain_days][google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_retain_days]
    /// must also be defined.
    ///
    /// Default (empty): no automatic backup creation will occur.
    ///
    /// [google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_retain_days]: <doc:BackupPlan/RetentionPolicy/backupRetainDays>
    /// [google.cloud.gkebackup.v1.BackupPlan.Schedule.cron_schedule]: <doc:BackupPlan/Schedule/cronSchedule>
    public var rpoConfig: RpoConfig? = nil

    /// Output only. Start time of next scheduled backup under this BackupPlan by
    /// either cron_schedule or rpo config.
    public var nextScheduledBackupTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Schedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Schedule().with { $0.cronSchedule = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cronSchedule = CodingKeys(stringValue: "cronSchedule")
      static let paused = CodingKeys(stringValue: "paused")
      static let rpoConfig = CodingKeys(stringValue: "rpoConfig")
      static let nextScheduledBackupTime = CodingKeys(stringValue: "nextScheduledBackupTime")

      static let _knownKeys: Set<Swift.String> = [
        "cronSchedule",
        "paused",
        "rpoConfig",
        "nextScheduledBackupTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cronSchedule) {
        self.cronSchedule = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .paused) {
        self.paused = value
      }
      self.rpoConfig = try container.decodeIfPresent(RpoConfig.self, forKey: .rpoConfig)
      self.nextScheduledBackupTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .nextScheduledBackupTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cronSchedule, forKey: .cronSchedule)
      try container.encode(self.paused, forKey: .paused)
      try container.encodeIfPresent(self.rpoConfig, forKey: .rpoConfig)
      try container.encodeIfPresent(self.nextScheduledBackupTime, forKey: .nextScheduledBackupTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.BackupPlan.Schedule"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// BackupConfig defines the configuration of Backups created via this
  /// BackupPlan.
  public struct BackupConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. This flag specifies whether volume data should be backed up
    /// when PVCs are included in the scope of a Backup.
    ///
    /// Default: False
    public var includeVolumeData: Swift.Bool = Swift.Bool()

    /// Optional. This flag specifies whether Kubernetes Secret resources should
    /// be included when they fall into the scope of Backups.
    ///
    /// Default: False
    public var includeSecrets: Swift.Bool = Swift.Bool()

    /// Optional. This defines a customer managed encryption key that will be
    /// used to encrypt the "config" portion (the Kubernetes resources) of
    /// Backups created via this plan.
    ///
    /// Default (empty): Config backup artifacts will not be encrypted.
    public var encryptionKey: EncryptionKey? = nil

    /// Optional. If false, Backups will fail when Backup for GKE detects
    /// Kubernetes configuration that is non-standard or
    /// requires additional setup to restore.
    ///
    /// Default: False
    public var permissiveMode: Swift.Bool = Swift.Bool()

    /// This defines the "scope" of the Backup - which namespaced
    /// resources in the cluster will be included in a Backup.
    /// Exactly one of the fields of backup_scope MUST be specified.
    public var backupScope: BackupScopeOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BackupConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BackupConfig().with { $0.allNamespaces = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let allNamespaces = CodingKeys(stringValue: "allNamespaces")
      static let selectedNamespaces = CodingKeys(stringValue: "selectedNamespaces")
      static let selectedApplications = CodingKeys(stringValue: "selectedApplications")
      static let includeVolumeData = CodingKeys(stringValue: "includeVolumeData")
      static let includeSecrets = CodingKeys(stringValue: "includeSecrets")
      static let encryptionKey = CodingKeys(stringValue: "encryptionKey")
      static let permissiveMode = CodingKeys(stringValue: "permissiveMode")

      static let _knownKeys: Set<Swift.String> = [
        "allNamespaces",
        "selectedNamespaces",
        "selectedApplications",
        "includeVolumeData",
        "includeSecrets",
        "encryptionKey",
        "permissiveMode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .includeVolumeData) {
        self.includeVolumeData = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .includeSecrets) {
        self.includeSecrets = value
      }
      self.encryptionKey = try container.decodeIfPresent(EncryptionKey.self, forKey: .encryptionKey)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .permissiveMode) {
        self.permissiveMode = value
      }

      var backupScope: BackupScopeOneOf? = nil
      let backupScopeCheckAndSet = {
        if backupScope != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'backupScope'"))
        }
        backupScope = $0
      }
      if let allNamespaces = try container.decodeIfPresent(Swift.Bool.self, forKey: .allNamespaces)
      {
        try backupScopeCheckAndSet(.allNamespaces(allNamespaces))
      }
      if let selectedNamespaces = try container.decodeIfPresent(
        Namespaces?.self, forKey: .selectedNamespaces)
      {
        try backupScopeCheckAndSet(.selectedNamespaces(selectedNamespaces))
      }
      if let selectedApplications = try container.decodeIfPresent(
        NamespacedNames?.self, forKey: .selectedApplications)
      {
        try backupScopeCheckAndSet(.selectedApplications(selectedApplications))
      }
      self.backupScope = backupScope
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.includeVolumeData, forKey: .includeVolumeData)
      try container.encode(self.includeSecrets, forKey: .includeSecrets)
      try container.encodeIfPresent(self.encryptionKey, forKey: .encryptionKey)
      try container.encode(self.permissiveMode, forKey: .permissiveMode)

      if let choice = self.backupScope {
        switch choice {
        case .allNamespaces(let value):
          try container.encode(value, forKey: .allNamespaces)
        case .selectedNamespaces(let value):
          try container.encode(value, forKey: .selectedNamespaces)
        case .selectedApplications(let value):
          try container.encode(value, forKey: .selectedApplications)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// This defines the "scope" of the Backup - which namespaced
    /// resources in the cluster will be included in a Backup.
    /// Exactly one of the fields of backup_scope MUST be specified.
    public enum BackupScopeOneOf: Codable, Equatable, Sendable {
      /// If True, include all namespaced resources
      case allNamespaces(Swift.Bool)
      /// If set, include just the resources in the listed namespaces.
      indirect case selectedNamespaces(Namespaces?)
      /// If set, include just the resources referenced by the listed
      /// ProtectedApplications.
      indirect case selectedApplications(NamespacedNames?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.BackupPlan.BackupConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// State
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Default first value for Enums.
    case unspecified
    /// Waiting for cluster state to be RUNNING.
    case clusterPending
    /// The BackupPlan is in the process of being created.
    case provisioning
    /// The BackupPlan has successfully been created and is ready for Backups.
    case ready
    /// BackupPlan creation has failed.
    case failed
    /// The BackupPlan has been deactivated.
    case deactivated
    /// The BackupPlan is in the process of being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .clusterPending: return 1
      case .provisioning: return 2
      case .ready: return 3
      case .failed: return 4
      case .deactivated: return 5
      case .deleting: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .clusterPending: return "CLUSTER_PENDING"
      case .provisioning: return "PROVISIONING"
      case .ready: return "READY"
      case .failed: return "FAILED"
      case .deactivated: return "DEACTIVATED"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CLUSTER_PENDING": self = .clusterPending
      case "PROVISIONING": self = .provisioning
      case "READY": self = .ready
      case "FAILED": self = .failed
      case "DEACTIVATED": self = .deactivated
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .clusterPending
      case 2: self = .provisioning
      case 3: self = .ready
      case 4: self = .failed
      case 5: self = .deactivated
      case 6: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .clusterPending: return try container.encode("CLUSTER_PENDING")
      case .provisioning: return try container.encode("PROVISIONING")
      case .ready: return try container.encode("READY")
      case .failed: return try container.encode("FAILED")
      case .deactivated: return try container.encode("DEACTIVATED")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.BackupPlan"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
