// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class BackupForGKELogging: BackupForGKEStub {
    let inner: any BackupForGKEStub
    let logger: Logger

    public init(_ inner: any BackupForGKEStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-gkebackup-v1"
      logger[metadataKey: "gcp.client.service"] = "gkebackup"
      logger[metadataKey: "gcp.experimental.swift.client"] = "BackupForGKE"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createBackupPlan(
      request: CreateBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackupPlan",
        action: {
          (r: CreateBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupPlan(request: r, options: o)
        })
    }

    public func listBackupPlans(
      request: ListBackupPlansRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupPlansResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackupPlans",
        action: {
          (r: ListBackupPlansRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListBackupPlansResponse
          in
          return try await self.inner.listBackupPlans(request: r, options: o)
        })
    }

    public func getBackupPlan(
      request: GetBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.BackupPlan {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupPlan",
        action: {
          (r: GetBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.BackupPlan
          in
          return try await self.inner.getBackupPlan(request: r, options: o)
        })
    }

    public func updateBackupPlan(
      request: UpdateBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackupPlan",
        action: {
          (r: UpdateBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupPlan(request: r, options: o)
        })
    }

    public func deleteBackupPlan(
      request: DeleteBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackupPlan",
        action: {
          (r: DeleteBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupPlan(request: r, options: o)
        })
    }

    public func createBackupChannel(
      request: CreateBackupChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackupChannel",
        action: {
          (r: CreateBackupChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupChannel(request: r, options: o)
        })
    }

    public func listBackupChannels(
      request: ListBackupChannelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupChannelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackupChannels",
        action: {
          (r: ListBackupChannelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListBackupChannelsResponse
          in
          return try await self.inner.listBackupChannels(request: r, options: o)
        })
    }

    public func getBackupChannel(
      request: GetBackupChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.BackupChannel {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupChannel",
        action: {
          (r: GetBackupChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.BackupChannel
          in
          return try await self.inner.getBackupChannel(request: r, options: o)
        })
    }

    public func updateBackupChannel(
      request: UpdateBackupChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackupChannel",
        action: {
          (r: UpdateBackupChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupChannel(request: r, options: o)
        })
    }

    public func deleteBackupChannel(
      request: DeleteBackupChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackupChannel",
        action: {
          (r: DeleteBackupChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupChannel(request: r, options: o)
        })
    }

    public func listBackupPlanBindings(
      request: ListBackupPlanBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupPlanBindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackupPlanBindings",
        action: {
          (r: ListBackupPlanBindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListBackupPlanBindingsResponse
          in
          return try await self.inner.listBackupPlanBindings(request: r, options: o)
        })
    }

    public func getBackupPlanBinding(
      request: GetBackupPlanBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.BackupPlanBinding {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupPlanBinding",
        action: {
          (r: GetBackupPlanBindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.BackupPlanBinding
          in
          return try await self.inner.getBackupPlanBinding(request: r, options: o)
        })
    }

    public func createBackup(
      request: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackup",
        action: {
          (r: CreateBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackup(request: r, options: o)
        })
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListBackupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackups",
        action: {
          (r: ListBackupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListBackupsResponse
          in
          return try await self.inner.listBackups(request: r, options: o)
        })
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.Backup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackup",
        action: {
          (r: GetBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.Backup
          in
          return try await self.inner.getBackup(request: r, options: o)
        })
    }

    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackup",
        action: {
          (r: UpdateBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackup(request: r, options: o)
        })
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackup",
        action: {
          (r: DeleteBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackup(request: r, options: o)
        })
    }

    public func listVolumeBackups(
      request: ListVolumeBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListVolumeBackupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVolumeBackups",
        action: {
          (r: ListVolumeBackupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListVolumeBackupsResponse
          in
          return try await self.inner.listVolumeBackups(request: r, options: o)
        })
    }

    public func getVolumeBackup(
      request: GetVolumeBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.VolumeBackup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVolumeBackup",
        action: {
          (r: GetVolumeBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.VolumeBackup
          in
          return try await self.inner.getVolumeBackup(request: r, options: o)
        })
    }

    public func createRestorePlan(
      request: CreateRestorePlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRestorePlan",
        action: {
          (r: CreateRestorePlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createRestorePlan(request: r, options: o)
        })
    }

    public func listRestorePlans(
      request: ListRestorePlansRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestorePlansResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRestorePlans",
        action: {
          (r: ListRestorePlansRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListRestorePlansResponse
          in
          return try await self.inner.listRestorePlans(request: r, options: o)
        })
    }

    public func getRestorePlan(
      request: GetRestorePlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.RestorePlan {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRestorePlan",
        action: {
          (r: GetRestorePlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.RestorePlan
          in
          return try await self.inner.getRestorePlan(request: r, options: o)
        })
    }

    public func updateRestorePlan(
      request: UpdateRestorePlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRestorePlan",
        action: {
          (r: UpdateRestorePlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateRestorePlan(request: r, options: o)
        })
    }

    public func deleteRestorePlan(
      request: DeleteRestorePlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRestorePlan",
        action: {
          (r: DeleteRestorePlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRestorePlan(request: r, options: o)
        })
    }

    public func createRestoreChannel(
      request: CreateRestoreChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRestoreChannel",
        action: {
          (r: CreateRestoreChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createRestoreChannel(request: r, options: o)
        })
    }

    public func listRestoreChannels(
      request: ListRestoreChannelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestoreChannelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRestoreChannels",
        action: {
          (r: ListRestoreChannelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListRestoreChannelsResponse
          in
          return try await self.inner.listRestoreChannels(request: r, options: o)
        })
    }

    public func getRestoreChannel(
      request: GetRestoreChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.RestoreChannel {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRestoreChannel",
        action: {
          (r: GetRestoreChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.RestoreChannel
          in
          return try await self.inner.getRestoreChannel(request: r, options: o)
        })
    }

    public func updateRestoreChannel(
      request: UpdateRestoreChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRestoreChannel",
        action: {
          (r: UpdateRestoreChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateRestoreChannel(request: r, options: o)
        })
    }

    public func deleteRestoreChannel(
      request: DeleteRestoreChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRestoreChannel",
        action: {
          (r: DeleteRestoreChannelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRestoreChannel(request: r, options: o)
        })
    }

    public func listRestorePlanBindings(
      request: ListRestorePlanBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestorePlanBindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRestorePlanBindings",
        action: {
          (r: ListRestorePlanBindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListRestorePlanBindingsResponse
          in
          return try await self.inner.listRestorePlanBindings(request: r, options: o)
        })
    }

    public func getRestorePlanBinding(
      request: GetRestorePlanBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.RestorePlanBinding {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRestorePlanBinding",
        action: {
          (r: GetRestorePlanBindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.RestorePlanBinding
          in
          return try await self.inner.getRestorePlanBinding(request: r, options: o)
        })
    }

    public func createRestore(
      request: CreateRestoreRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRestore",
        action: {
          (r: CreateRestoreRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createRestore(request: r, options: o)
        })
    }

    public func listRestores(
      request: ListRestoresRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListRestoresResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRestores",
        action: {
          (r: ListRestoresRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListRestoresResponse
          in
          return try await self.inner.listRestores(request: r, options: o)
        })
    }

    public func getRestore(
      request: GetRestoreRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.Restore {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRestore",
        action: {
          (r: GetRestoreRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.Restore
          in
          return try await self.inner.getRestore(request: r, options: o)
        })
    }

    public func updateRestore(
      request: UpdateRestoreRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRestore",
        action: {
          (r: UpdateRestoreRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateRestore(request: r, options: o)
        })
    }

    public func deleteRestore(
      request: DeleteRestoreRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRestore",
        action: {
          (r: DeleteRestoreRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRestore(request: r, options: o)
        })
    }

    public func listVolumeRestores(
      request: ListVolumeRestoresRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.ListVolumeRestoresResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVolumeRestores",
        action: {
          (r: ListVolumeRestoresRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.ListVolumeRestoresResponse
          in
          return try await self.inner.listVolumeRestores(request: r, options: o)
        })
    }

    public func getVolumeRestore(
      request: GetVolumeRestoreRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.VolumeRestore {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVolumeRestore",
        action: {
          (r: GetVolumeRestoreRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.VolumeRestore
          in
          return try await self.inner.getVolumeRestore(request: r, options: o)
        })
    }

    public func getBackupIndexDownloadUrl(
      request: GetBackupIndexDownloadUrlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEBackupV1.GetBackupIndexDownloadUrlResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupIndexDownloadUrl",
        action: {
          (r: GetBackupIndexDownloadUrlRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEBackupV1.GetBackupIndexDownloadUrlResponse
          in
          return try await self.inner.getBackupIndexDownloadUrl(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
