// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a request to perform a single point-in-time capture of
/// some portion of the state of a GKE cluster, the record of the backup
/// operation itself, and an anchor for the underlying artifacts that
/// comprise the Backup (the config backup and VolumeBackups).
public struct Backup: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The fully qualified name of the Backup.
  /// `projects/*/locations/*/backupPlans/*/backups/*`
  public var name: Swift.String = Swift.String()

  /// Output only. Server generated global unique identifier of
  /// [UUID4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
  public var uid: Swift.String = Swift.String()

  /// Output only. The timestamp when this Backup resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when this Backup resource was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. This flag indicates whether this Backup resource was created
  /// manually by a user or via a schedule in the BackupPlan. A value of True
  /// means that the Backup was created manually.
  public var manual: Swift.Bool = Swift.Bool()

  /// Optional. A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Minimum age for this Backup (in days). If this field is set to a
  /// non-zero value, the Backup will be "locked" against deletion (either manual
  /// or automatic deletion) for the number of days provided (measured from the
  /// creation time of the Backup).  MUST be an integer value between 0-90
  /// (inclusive).
  ///
  /// Defaults to parent BackupPlan's
  /// [backup_delete_lock_days][google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_delete_lock_days]
  /// setting and may only be increased
  /// (either at creation time or in a subsequent update).
  ///
  /// [google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_delete_lock_days]: <doc:BackupPlan/RetentionPolicy/backupDeleteLockDays>
  public var deleteLockDays: Swift.Int32 = Swift.Int32()

  /// Output only. The time at which an existing delete lock will expire for this
  /// backup (calculated from create_time +
  /// [delete_lock_days][google.cloud.gkebackup.v1.Backup.delete_lock_days]).
  ///
  /// [google.cloud.gkebackup.v1.Backup.delete_lock_days]: <doc:Backup/deleteLockDays>
  public var deleteLockExpireTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The age (in days) after which this Backup will be automatically
  /// deleted. Must be an integer value >= 0:
  ///
  /// - If 0, no automatic deletion will occur for this Backup.
  /// - If not 0, this must be >=
  /// [delete_lock_days][google.cloud.gkebackup.v1.Backup.delete_lock_days] and
  /// <= 365.
  ///
  /// Once a Backup is created, this value may only be increased.
  ///
  /// Defaults to the parent BackupPlan's
  /// [backup_retain_days][google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_retain_days]
  /// value.
  ///
  /// [google.cloud.gkebackup.v1.Backup.delete_lock_days]: <doc:Backup/deleteLockDays>
  /// [google.cloud.gkebackup.v1.BackupPlan.RetentionPolicy.backup_retain_days]: <doc:BackupPlan/RetentionPolicy/backupRetainDays>
  public var retainDays: Swift.Int32 = Swift.Int32()

  /// Output only. The time at which this Backup will be automatically deleted
  /// (calculated from create_time +
  /// [retain_days][google.cloud.gkebackup.v1.Backup.retain_days]).
  ///
  /// [google.cloud.gkebackup.v1.Backup.retain_days]: <doc:Backup/retainDays>
  public var retainExpireTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The customer managed encryption key that was used to encrypt
  /// the Backup's artifacts.  Inherited from the parent BackupPlan's
  /// [encryption_key][google.cloud.gkebackup.v1.BackupPlan.BackupConfig.encryption_key]
  /// value.
  ///
  /// [google.cloud.gkebackup.v1.BackupPlan.BackupConfig.encryption_key]: <doc:BackupPlan/BackupConfig/encryptionKey>
  public var encryptionKey: EncryptionKey? = nil

  /// Output only. Whether or not the Backup contains volume data.  Controlled by
  /// the parent BackupPlan's
  /// [include_volume_data][google.cloud.gkebackup.v1.BackupPlan.BackupConfig.include_volume_data]
  /// value.
  ///
  /// [google.cloud.gkebackup.v1.BackupPlan.BackupConfig.include_volume_data]: <doc:BackupPlan/BackupConfig/includeVolumeData>
  public var containsVolumeData: Swift.Bool = Swift.Bool()

  /// Output only. Whether or not the Backup contains Kubernetes Secrets.
  /// Controlled by the parent BackupPlan's
  /// [include_secrets][google.cloud.gkebackup.v1.BackupPlan.BackupConfig.include_secrets]
  /// value.
  ///
  /// [google.cloud.gkebackup.v1.BackupPlan.BackupConfig.include_secrets]: <doc:BackupPlan/BackupConfig/includeSecrets>
  public var containsSecrets: Swift.Bool = Swift.Bool()

  /// Output only. Information about the GKE cluster from which this Backup was
  /// created.
  public var clusterMetadata: Backup.ClusterMetadata? = nil

  /// Output only. Current state of the Backup
  public var state: Backup.State = Backup.State()

  /// Output only. Human-readable description of why the backup is in the current
  /// `state`. This field is only meant for human readability and should not be
  /// used programmatically as this field is not guaranteed to be consistent.
  public var stateReason: Swift.String = Swift.String()

  /// Output only. Completion time of the Backup
  public var completeTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The total number of Kubernetes resources included in the
  /// Backup.
  public var resourceCount: Swift.Int32 = Swift.Int32()

  /// Output only. The total number of volume backups contained in the Backup.
  public var volumeCount: Swift.Int32 = Swift.Int32()

  /// Output only. The total size of the Backup in bytes = config backup size +
  /// sum(volume backup sizes)
  public var sizeBytes: Swift.Int64 = Swift.Int64()

  /// Output only. `etag` is used for optimistic concurrency control as a way to
  /// help prevent simultaneous updates of a backup from overwriting each other.
  /// It is strongly suggested that systems make use of the `etag` in the
  /// read-modify-write cycle to perform backup updates in order to avoid
  /// race conditions: An `etag` is returned in the response to `GetBackup`,
  /// and systems are expected to put that etag in the request to
  /// `UpdateBackup` or `DeleteBackup` to ensure that their change will be
  /// applied to the same version of the resource.
  public var etag: Swift.String = Swift.String()

  /// Optional. User specified descriptive string for this Backup.
  public var description: Swift.String = Swift.String()

  /// Output only. The total number of Kubernetes Pods contained in the Backup.
  public var podCount: Swift.Int32 = Swift.Int32()

  /// Output only. The size of the config backup in bytes.
  public var configBackupSizeBytes: Swift.Int64 = Swift.Int64()

  /// Output only. If false, Backup will fail when Backup for GKE detects
  /// Kubernetes configuration that is non-standard or
  /// requires additional setup to restore.
  ///
  /// Inherited from the parent BackupPlan's
  /// [permissive_mode][google.cloud.gkebackup.v1.BackupPlan.BackupConfig.permissive_mode]
  /// value.
  ///
  /// [google.cloud.gkebackup.v1.BackupPlan.BackupConfig.permissive_mode]: <doc:BackupPlan/BackupConfig/permissiveMode>
  public var permissiveMode: Swift.Bool = Swift.Bool()

  /// Output only. [Output Only] Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. [Output Only] Reserved for future use.
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Defines the "scope" of the Backup - which namespaced resources in the
  /// cluster were included in the Backup.  Inherited from the parent
  /// BackupPlan's
  /// [backup_scope][google.cloud.gkebackup.v1.BackupPlan.BackupConfig.backup_scope]
  /// value.
  ///
  /// [google.cloud.gkebackup.v1.BackupPlan.BackupConfig.backup_scope]: <doc:BackupPlan/BackupConfig/BackupScopeOneOf>
  public var backupScope: BackupScopeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Backup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Backup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let manual = CodingKeys(stringValue: "manual")
    static let labels = CodingKeys(stringValue: "labels")
    static let deleteLockDays = CodingKeys(stringValue: "deleteLockDays")
    static let deleteLockExpireTime = CodingKeys(stringValue: "deleteLockExpireTime")
    static let retainDays = CodingKeys(stringValue: "retainDays")
    static let retainExpireTime = CodingKeys(stringValue: "retainExpireTime")
    static let encryptionKey = CodingKeys(stringValue: "encryptionKey")
    static let allNamespaces = CodingKeys(stringValue: "allNamespaces")
    static let selectedNamespaces = CodingKeys(stringValue: "selectedNamespaces")
    static let selectedApplications = CodingKeys(stringValue: "selectedApplications")
    static let containsVolumeData = CodingKeys(stringValue: "containsVolumeData")
    static let containsSecrets = CodingKeys(stringValue: "containsSecrets")
    static let clusterMetadata = CodingKeys(stringValue: "clusterMetadata")
    static let state = CodingKeys(stringValue: "state")
    static let stateReason = CodingKeys(stringValue: "stateReason")
    static let completeTime = CodingKeys(stringValue: "completeTime")
    static let resourceCount = CodingKeys(stringValue: "resourceCount")
    static let volumeCount = CodingKeys(stringValue: "volumeCount")
    static let sizeBytes = CodingKeys(stringValue: "sizeBytes")
    static let etag = CodingKeys(stringValue: "etag")
    static let description = CodingKeys(stringValue: "description")
    static let podCount = CodingKeys(stringValue: "podCount")
    static let configBackupSizeBytes = CodingKeys(stringValue: "configBackupSizeBytes")
    static let permissiveMode = CodingKeys(stringValue: "permissiveMode")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let satisfiesPzi = CodingKeys(stringValue: "satisfiesPzi")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "createTime",
      "updateTime",
      "manual",
      "labels",
      "deleteLockDays",
      "deleteLockExpireTime",
      "retainDays",
      "retainExpireTime",
      "encryptionKey",
      "allNamespaces",
      "selectedNamespaces",
      "selectedApplications",
      "containsVolumeData",
      "containsSecrets",
      "clusterMetadata",
      "state",
      "stateReason",
      "completeTime",
      "resourceCount",
      "volumeCount",
      "sizeBytes",
      "etag",
      "description",
      "podCount",
      "configBackupSizeBytes",
      "permissiveMode",
      "satisfiesPzs",
      "satisfiesPzi",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .manual) {
      self.manual = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .deleteLockDays) {
      self.deleteLockDays = value
    }
    self.deleteLockExpireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteLockExpireTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .retainDays) {
      self.retainDays = value
    }
    self.retainExpireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .retainExpireTime)
    self.encryptionKey = try container.decodeIfPresent(EncryptionKey.self, forKey: .encryptionKey)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .containsVolumeData) {
      self.containsVolumeData = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .containsSecrets) {
      self.containsSecrets = value
    }
    self.clusterMetadata = try container.decodeIfPresent(
      Backup.ClusterMetadata.self, forKey: .clusterMetadata)
    if let value = try container.decodeIfPresent(Backup.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateReason) {
      self.stateReason = value
    }
    self.completeTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .completeTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .resourceCount) {
      self.resourceCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .volumeCount) {
      self.volumeCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sizeBytes) {
      self.sizeBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .podCount) {
      self.podCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .configBackupSizeBytes) {
      self.configBackupSizeBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .permissiveMode) {
      self.permissiveMode = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi) {
      self.satisfiesPzi = value
    }

    var backupScope: BackupScopeOneOf? = nil
    let backupScopeCheckAndSet = {
      if backupScope != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'backupScope'"))
      }
      backupScope = $0
    }
    if let allNamespaces = try container.decodeIfPresent(Swift.Bool.self, forKey: .allNamespaces) {
      try backupScopeCheckAndSet(.allNamespaces(allNamespaces))
    }
    if let selectedNamespaces = try container.decodeIfPresent(
      Namespaces?.self, forKey: .selectedNamespaces)
    {
      try backupScopeCheckAndSet(.selectedNamespaces(selectedNamespaces))
    }
    if let selectedApplications = try container.decodeIfPresent(
      NamespacedNames?.self, forKey: .selectedApplications)
    {
      try backupScopeCheckAndSet(.selectedApplications(selectedApplications))
    }
    self.backupScope = backupScope
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.manual, forKey: .manual)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.deleteLockDays, forKey: .deleteLockDays)
    try container.encodeIfPresent(self.deleteLockExpireTime, forKey: .deleteLockExpireTime)
    try container.encode(self.retainDays, forKey: .retainDays)
    try container.encodeIfPresent(self.retainExpireTime, forKey: .retainExpireTime)
    try container.encodeIfPresent(self.encryptionKey, forKey: .encryptionKey)
    try container.encode(self.containsVolumeData, forKey: .containsVolumeData)
    try container.encode(self.containsSecrets, forKey: .containsSecrets)
    try container.encodeIfPresent(self.clusterMetadata, forKey: .clusterMetadata)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateReason, forKey: .stateReason)
    try container.encodeIfPresent(self.completeTime, forKey: .completeTime)
    try container.encode(self.resourceCount, forKey: .resourceCount)
    try container.encode(self.volumeCount, forKey: .volumeCount)
    try container.encode(self.sizeBytes, forKey: .sizeBytes)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.podCount, forKey: .podCount)
    try container.encode(self.configBackupSizeBytes, forKey: .configBackupSizeBytes)
    try container.encode(self.permissiveMode, forKey: .permissiveMode)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)

    if let choice = self.backupScope {
      switch choice {
      case .allNamespaces(let value):
        try container.encode(value, forKey: .allNamespaces)
      case .selectedNamespaces(let value):
        try container.encode(value, forKey: .selectedNamespaces)
      case .selectedApplications(let value):
        try container.encode(value, forKey: .selectedApplications)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Information about the GKE cluster from which this Backup was created.
  public struct ClusterMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The source cluster from which this Backup was created.
    /// Valid formats:
    ///
    ///   - `projects/*/locations/*/clusters/*`
    ///   - `projects/*/zones/*/clusters/*`
    ///
    /// This is inherited from the parent BackupPlan's
    /// [cluster][google.cloud.gkebackup.v1.BackupPlan.cluster] field.
    ///
    /// [google.cloud.gkebackup.v1.BackupPlan.cluster]: <doc:BackupPlan/cluster>
    public var cluster: Swift.String = Swift.String()

    /// Output only. The Kubernetes server version of the source cluster.
    public var k8SVersion: Swift.String = Swift.String()

    /// Output only. A list of the Backup for GKE CRD versions found in the
    /// cluster.
    public var backupCrdVersions: [Swift.String: Swift.String] = [:]

    /// Platform-specific version
    public var platformVersion: PlatformVersionOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ClusterMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClusterMetadata().with { $0.cluster = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cluster = CodingKeys(stringValue: "cluster")
      static let k8SVersion = CodingKeys(stringValue: "k8sVersion")
      static let backupCrdVersions = CodingKeys(stringValue: "backupCrdVersions")
      static let gkeVersion = CodingKeys(stringValue: "gkeVersion")
      static let anthosVersion = CodingKeys(stringValue: "anthosVersion")

      static let _knownKeys: Set<Swift.String> = [
        "cluster",
        "k8sVersion",
        "backupCrdVersions",
        "gkeVersion",
        "anthosVersion",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
        self.cluster = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .k8SVersion) {
        self.k8SVersion = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .backupCrdVersions)
      {
        self.backupCrdVersions = value
      }

      var platformVersion: PlatformVersionOneOf? = nil
      let platformVersionCheckAndSet = {
        if platformVersion != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'platformVersion'"))
        }
        platformVersion = $0
      }
      if let gkeVersion = try container.decodeIfPresent(Swift.String.self, forKey: .gkeVersion) {
        try platformVersionCheckAndSet(.gkeVersion(gkeVersion))
      }
      if let anthosVersion = try container.decodeIfPresent(
        Swift.String.self, forKey: .anthosVersion)
      {
        try platformVersionCheckAndSet(.anthosVersion(anthosVersion))
      }
      self.platformVersion = platformVersion
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cluster, forKey: .cluster)
      try container.encode(self.k8SVersion, forKey: .k8SVersion)
      try container.encode(self.backupCrdVersions, forKey: .backupCrdVersions)

      if let choice = self.platformVersion {
        switch choice {
        case .gkeVersion(let value):
          try container.encode(value, forKey: .gkeVersion)
        case .anthosVersion(let value):
          try container.encode(value, forKey: .anthosVersion)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Platform-specific version
    public enum PlatformVersionOneOf: Codable, Equatable, Sendable {
      /// Output only. GKE version
      case gkeVersion(Swift.String)
      /// Output only. Anthos version
      case anthosVersion(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.Backup.ClusterMetadata"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// State
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// The Backup resource is in the process of being created.
    case unspecified
    /// The Backup resource has been created and the associated BackupJob
    /// Kubernetes resource has been injected into the source cluster.
    case creating
    /// The gkebackup agent in the cluster has begun executing the backup
    /// operation.
    case inProgress
    /// The backup operation has completed successfully.
    case succeeded
    /// The backup operation has failed.
    case failed
    /// This Backup resource (and its associated artifacts) is in the process
    /// of being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .inProgress: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .deleting: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .inProgress: return "IN_PROGRESS"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "IN_PROGRESS": self = .inProgress
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .inProgress
      case 3: self = .succeeded
      case 4: self = .failed
      case 5: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines the "scope" of the Backup - which namespaced resources in the
  /// cluster were included in the Backup.  Inherited from the parent
  /// BackupPlan's
  /// [backup_scope][google.cloud.gkebackup.v1.BackupPlan.BackupConfig.backup_scope]
  /// value.
  ///
  /// [google.cloud.gkebackup.v1.BackupPlan.BackupConfig.backup_scope]: <doc:BackupPlan/BackupConfig/BackupScopeOneOf>
  public enum BackupScopeOneOf: Codable, Equatable, Sendable {
    /// Output only. If True, all namespaces were included in the Backup.
    case allNamespaces(Swift.Bool)
    /// Output only. If set, the list of namespaces that were included in the
    /// Backup.
    indirect case selectedNamespaces(Namespaces?)
    /// Output only. If set, the list of ProtectedApplications whose resources
    /// were included in the Backup.
    indirect case selectedApplications(NamespacedNames?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.Backup"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
