// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for CreateBackupChannel.
public struct CreateBackupChannelRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The location within which to create the BackupChannel.
  /// Format: `projects/*/locations/*`
  public var parent: Swift.String = Swift.String()

  /// Required. The BackupChannel resource object to create.
  public var backupChannel: BackupChannel? = nil

  /// Optional. The client-provided short name for the BackupChannel resource.
  /// This name must:
  ///
  /// - be between 1 and 63 characters long (inclusive)
  /// - consist of only lower-case ASCII letters, numbers, and dashes
  /// - start with a lower-case letter
  /// - end with a lower-case letter or number
  /// - be unique within the set of BackupChannels in this location
  /// If the user does not provide a name, a uuid will be used as the name.
  public var backupChannelId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateBackupChannelRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateBackupChannelRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.CreateBackupChannelRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
