// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for CreateBackupChannel.
public struct CreateBackupChannelRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The location within which to create the BackupChannel.
  /// Format: `projects/*/locations/*`
  public var parent: Swift.String = Swift.String()

  /// Required. The BackupChannel resource object to create.
  public var backupChannel: BackupChannel? = nil

  /// Optional. The client-provided short name for the BackupChannel resource.
  /// This name must:
  ///
  /// - be between 1 and 63 characters long (inclusive)
  /// - consist of only lower-case ASCII letters, numbers, and dashes
  /// - start with a lower-case letter
  /// - end with a lower-case letter or number
  /// - be unique within the set of BackupChannels in this location
  /// If the user does not provide a name, a uuid will be used as the name.
  public var backupChannelId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateBackupChannelRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateBackupChannelRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let backupChannel = CodingKeys(stringValue: "backupChannel")
    static let backupChannelId = CodingKeys(stringValue: "backupChannelId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "backupChannel",
      "backupChannelId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.backupChannel = try container.decodeIfPresent(BackupChannel.self, forKey: .backupChannel)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupChannelId) {
      self.backupChannelId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.backupChannel, forKey: .backupChannel)
    try container.encode(self.backupChannelId, forKey: .backupChannelId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.CreateBackupChannelRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
