// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for CreateRestore.
public struct CreateRestoreRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The RestorePlan within which to create the Restore.
  /// Format: `projects/*/locations/*/restorePlans/*`
  public var parent: Swift.String = Swift.String()

  /// Required. The restore resource to create.
  public var restore: Restore? = nil

  /// Required. The client-provided short name for the Restore resource.
  /// This name must:
  ///
  /// - be between 1 and 63 characters long (inclusive)
  /// - consist of only lower-case ASCII letters, numbers, and dashes
  /// - start with a lower-case letter
  /// - end with a lower-case letter or number
  /// - be unique within the set of Restores in this RestorePlan.
  public var restoreId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateRestoreRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateRestoreRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let restore = CodingKeys(stringValue: "restore")
    static let restoreId = CodingKeys(stringValue: "restoreId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "restore",
      "restoreId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.restore = try container.decodeIfPresent(Restore.self, forKey: .restore)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .restoreId) {
      self.restoreId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.restore, forKey: .restore)
    try container.encode(self.restoreId, forKey: .restoreId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.CreateRestoreRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
