// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Defines a time window during which no backup should
/// happen. All time and date are in UTC.
public struct ExclusionWindow: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Specifies the start time of the window using time of the day in
  /// UTC.
  public var startTime: GoogleType.TimeOfDay? = nil

  /// Required. Specifies duration of the window.
  /// Duration must be >= 5 minutes and < (target RPO - 20 minutes).
  /// Additional restrictions based on the recurrence type to allow some time for
  /// backup to happen:
  /// - single_occurrence_date:  no restriction, but UI may warn about this when
  /// duration >= target RPO
  /// - daily window: duration < 24 hours
  /// - weekly window:
  ///   - days of week includes all seven days of a week: duration < 24 hours
  ///   - all other weekly window: duration < 168 hours (i.e., 24 * 7 hours)
  public var duration: GoogleCloudWKT.Duration? = nil

  /// Required. Specifies the day(s) on which the exclusion window takes
  /// effect. Exactly one of the fields MUST be specified.
  public var recurrence: OneOf_Recurrence? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExclusionWindow`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExclusionWindow().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let startTime = CodingKeys(stringValue: "startTime")
    static let duration = CodingKeys(stringValue: "duration")
    static let singleOccurrenceDate = CodingKeys(stringValue: "singleOccurrenceDate")
    static let daily = CodingKeys(stringValue: "daily")
    static let daysOfWeek = CodingKeys(stringValue: "daysOfWeek")

    static let _knownKeys: Set<Swift.String> = [
      "startTime",
      "duration",
      "singleOccurrenceDate",
      "daily",
      "daysOfWeek",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(GoogleType.TimeOfDay.self, forKey: .startTime)
    self.duration = try container.decodeIfPresent(GoogleCloudWKT.Duration.self, forKey: .duration)

    var recurrence: OneOf_Recurrence? = nil
    let recurrenceCheckAndSet = {
      if recurrence != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'recurrence'"))
      }
      recurrence = $0
    }
    if let singleOccurrenceDate = try container.decodeIfPresent(
      GoogleType.Date?.self, forKey: .singleOccurrenceDate)
    {
      try recurrenceCheckAndSet(.singleOccurrenceDate(singleOccurrenceDate))
    }
    if let daily = try container.decodeIfPresent(Swift.Bool.self, forKey: .daily) {
      try recurrenceCheckAndSet(.daily(daily))
    }
    if let daysOfWeek = try container.decodeIfPresent(
      ExclusionWindow.DayOfWeekList?.self, forKey: .daysOfWeek)
    {
      try recurrenceCheckAndSet(.daysOfWeek(daysOfWeek))
    }
    self.recurrence = recurrence
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.duration, forKey: .duration)

    if let choice = self.recurrence {
      switch choice {
      case .singleOccurrenceDate(let value):
        try container.encode(value, forKey: .singleOccurrenceDate)
      case .daily(let value):
        try container.encode(value, forKey: .daily)
      case .daysOfWeek(let value):
        try container.encode(value, forKey: .daysOfWeek)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Holds repeated DaysOfWeek values as a container.
  public struct DayOfWeekList: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. A list of days of week.
    public var daysOfWeek: [GoogleType.DayOfWeek] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `DayOfWeekList`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DayOfWeekList().with { $0.daysOfWeek = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let daysOfWeek = CodingKeys(stringValue: "daysOfWeek")

      static let _knownKeys: Set<Swift.String> = [
        "daysOfWeek"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([GoogleType.DayOfWeek].self, forKey: .daysOfWeek)
      {
        self.daysOfWeek = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.daysOfWeek, forKey: .daysOfWeek)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.ExclusionWindow.DayOfWeekList"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Required. Specifies the day(s) on which the exclusion window takes
  /// effect. Exactly one of the fields MUST be specified.
  public enum OneOf_Recurrence: Codable, Equatable, Sendable {
    /// No recurrence. The exclusion window occurs only once and on this
    /// date in UTC.
    indirect case singleOccurrenceDate(GoogleType.Date?)
    /// The exclusion window occurs every day if set to "True".
    /// Specifying this field to "False" is an error.
    case daily(Swift.Bool)
    /// The exclusion window occurs on these days of each week in UTC.
    indirect case daysOfWeek(ExclusionWindow.DayOfWeekList?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.ExclusionWindow"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
