// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for ListVolumeBackups.
public struct ListVolumeBackupsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The Backup that contains the VolumeBackups to list.
  /// Format: `projects/*/locations/*/backupPlans/*/backups/*`
  public var parent: Swift.String = Swift.String()

  /// Optional. The target number of results to return in a single response.
  /// If not specified, a default value will be chosen by the service.
  /// Note that the response may include a partial list and a caller should
  /// only rely on the response's
  /// [next_page_token][google.cloud.gkebackup.v1.ListVolumeBackupsResponse.next_page_token]
  /// to determine if there are more instances left to be queried.
  ///
  /// [google.cloud.gkebackup.v1.ListVolumeBackupsResponse.next_page_token]: <doc:ListVolumeBackupsResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The value of
  /// [next_page_token][google.cloud.gkebackup.v1.ListVolumeBackupsResponse.next_page_token]
  /// received from a previous `ListVolumeBackups` call.
  /// Provide this to retrieve the subsequent page in a multi-page list of
  /// results. When paginating, all other parameters provided to
  /// `ListVolumeBackups` must match the call that provided the page token.
  ///
  /// [google.cloud.gkebackup.v1.ListVolumeBackupsResponse.next_page_token]: <doc:ListVolumeBackupsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Field match expression used to filter the results.
  public var filter: Swift.String = Swift.String()

  /// Optional. Field by which to sort the results.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListVolumeBackupsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListVolumeBackupsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.ListVolumeBackupsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
