// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A RestoreChannel imposes constraints on where backups can be restored.
/// The RestoreChannel should be in the same project and region
/// as the backups. The backups can only be restored in the
/// `destination_project`.
public struct RestoreChannel: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The fully qualified name of the RestoreChannel.
  /// `projects/*/locations/*/restoreChannels/*`
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The project into which the backups will be restored.
  /// The format is `projects/{projectId}` or `projects/{projectNumber}`.
  public var destinationProject: Swift.String = Swift.String()

  /// Output only. Server generated global unique identifier of
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) format.
  public var uid: Swift.String = Swift.String()

  /// Output only. The timestamp when this RestoreChannel was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when this RestoreChannel was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. User specified descriptive string for this RestoreChannel.
  public var description: Swift.String = Swift.String()

  /// Output only. `etag` is used for optimistic concurrency control as a way to
  /// help prevent simultaneous updates of a RestoreChannel from overwriting each
  /// other. It is strongly suggested that systems make use of the 'etag' in the
  /// read-modify-write cycle to perform RestoreChannel updates in order to
  /// avoid race conditions: An `etag` is returned in the response to
  /// `GetRestoreChannel`, and systems are expected to put that etag in the
  /// request to `UpdateRestoreChannel` or `DeleteRestoreChannel` to
  /// ensure that their change will be applied to the same version of the
  /// resource.
  public var etag: Swift.String = Swift.String()

  /// Output only. The project_id where backups will be restored.
  /// Example Project ID: "my-project-id".
  /// This will be an OUTPUT_ONLY field to return the project_id of the
  /// destination project.
  public var destinationProjectId: Swift.String = Swift.String()

  /// Initialize a new instance of `RestoreChannel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreChannel().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreChannel"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
