// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A RestorePlanBinding binds a RestorePlan with a RestoreChannel.
/// This resource is created automatically when a RestorePlan is created using a
/// RestoreChannel. This also serves as a holder for cross-project fields
/// that need to be displayed in the current project.
public struct RestorePlanBinding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The fully qualified name of the RestorePlanBinding.
  /// `projects/*/locations/*/restoreChannels/*/restorePlanBindings/*`
  public var name: Swift.String = Swift.String()

  /// Output only. Server generated global unique identifier of
  /// [UUID4](https://en.wikipedia.org/wiki/Universally_unique_identifier)
  public var uid: Swift.String = Swift.String()

  /// Output only. The timestamp when this binding was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when this binding was created.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The fully qualified name of the RestorePlan bound to this
  /// RestoreChannel. `projects/*/locations/*/restorePlans/{restore_plan}`
  public var restorePlan: Swift.String = Swift.String()

  /// Output only. `etag` is used for optimistic concurrency control as a way to
  /// help prevent simultaneous updates of a RestorePlanBinding from overwriting
  /// each other. It is strongly suggested that systems make use of the 'etag' in
  /// the read-modify-write cycle to perform RestorePlanBinding updates in
  /// order to avoid race conditions: An `etag` is returned in the response to
  /// `GetRestorePlanBinding`, and systems are expected to put that etag in
  /// the request to `UpdateRestorePlanBinding` or
  /// `DeleteRestorePlanBinding` to ensure that their change will be applied
  /// to the same version of the resource.
  public var etag: Swift.String = Swift.String()

  /// Output only. The fully qualified name of the BackupPlan bound to the
  /// specified RestorePlan. `projects/*/locations/*/backukpPlans/{backup_plan}`
  public var backupPlan: Swift.String = Swift.String()

  /// Initialize a new instance of `RestorePlanBinding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestorePlanBinding().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.RestorePlanBinding"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
