// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration of a restore.
public struct RestoreConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Specifies the mechanism to be used to restore volume data.
  /// Default: VOLUME_DATA_RESTORE_POLICY_UNSPECIFIED (will be treated as
  /// NO_VOLUME_DATA_RESTORATION).
  public var volumeDataRestorePolicy: RestoreConfig.VolumeDataRestorePolicy =
    RestoreConfig.VolumeDataRestorePolicy()

  /// Optional. Defines the behavior for handling the situation where
  /// cluster-scoped resources being restored already exist in the target
  /// cluster. This MUST be set to a value other than
  /// CLUSTER_RESOURCE_CONFLICT_POLICY_UNSPECIFIED if
  /// [cluster_resource_restore_scope][google.cloud.gkebackup.v1.RestoreConfig.cluster_resource_restore_scope]
  /// is not empty.
  ///
  /// [google.cloud.gkebackup.v1.RestoreConfig.cluster_resource_restore_scope]: <doc:RestoreConfig/clusterResourceRestoreScope>
  public var clusterResourceConflictPolicy: RestoreConfig.ClusterResourceConflictPolicy =
    RestoreConfig.ClusterResourceConflictPolicy()

  /// Optional. Defines the behavior for handling the situation where sets of
  /// namespaced resources being restored already exist in the target cluster.
  /// This MUST be set to a value other than
  /// NAMESPACED_RESOURCE_RESTORE_MODE_UNSPECIFIED.
  public var namespacedResourceRestoreMode: RestoreConfig.NamespacedResourceRestoreMode =
    RestoreConfig.NamespacedResourceRestoreMode()

  /// Optional. Identifies the cluster-scoped resources to restore from the
  /// Backup. Not specifying it means NO cluster resource will be restored.
  public var clusterResourceRestoreScope: RestoreConfig.ClusterResourceRestoreScope? = nil

  /// Optional. A list of transformation rules to be applied against Kubernetes
  /// resources as they are selected for restoration from a Backup. Rules are
  /// executed in order defined - this order matters, as changes made by a rule
  /// may impact the filtering logic of subsequent rules. An empty list means no
  /// substitution will occur.
  public var substitutionRules: [RestoreConfig.SubstitutionRule] = []

  /// Optional. A list of transformation rules to be applied against Kubernetes
  /// resources as they are selected for restoration from a Backup. Rules are
  /// executed in order defined - this order matters, as changes made by a rule
  /// may impact the filtering logic of subsequent rules. An empty list means no
  /// transformation will occur.
  public var transformationRules: [RestoreConfig.TransformationRule] = []

  /// Optional. A table that binds volumes by their scope to a restore policy.
  /// Bindings must have a unique scope. Any volumes not scoped in the bindings
  /// are subject to the policy defined in volume_data_restore_policy.
  public var volumeDataRestorePolicyBindings: [RestoreConfig.VolumeDataRestorePolicyBinding] = []

  /// Optional. RestoreOrder contains custom ordering to use on a Restore.
  public var restoreOrder: RestoreConfig.RestoreOrder? = nil

  /// Specifies the namespaced resources to restore from the Backup.
  /// Only one of the entries may be specified. If not specified, NO namespaced
  /// resources will be restored.
  ///
  /// Note: Resources will never be restored into *managed* namespaces such as
  /// `kube-system`, `kube-public`, or `kube-node-lease`. These namespaces
  /// are silently skipped when
  /// [all_namespaces][google.cloud.gkebackup.v1.RestoreConfig.all_namespaces] is
  /// selected. Listing them explicitly will result in an error.
  ///
  /// [google.cloud.gkebackup.v1.RestoreConfig.all_namespaces]: <doc:RestoreConfig/allNamespaces>
  public var namespacedResourceRestoreScope: OneOf_NamespacedResourceRestoreScope? = nil

  /// Initialize a new instance of `RestoreConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreConfig().with { $0.volumeDataRestorePolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case volumeDataRestorePolicy = "volumeDataRestorePolicy"
    case clusterResourceConflictPolicy = "clusterResourceConflictPolicy"
    case namespacedResourceRestoreMode = "namespacedResourceRestoreMode"
    case clusterResourceRestoreScope = "clusterResourceRestoreScope"
    case allNamespaces = "allNamespaces"
    case selectedNamespaces = "selectedNamespaces"
    case selectedApplications = "selectedApplications"
    case noNamespaces = "noNamespaces"
    case excludedNamespaces = "excludedNamespaces"
    case substitutionRules = "substitutionRules"
    case transformationRules = "transformationRules"
    case volumeDataRestorePolicyBindings = "volumeDataRestorePolicyBindings"
    case restoreOrder = "restoreOrder"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.volumeDataRestorePolicy = try container.decode(
      RestoreConfig.VolumeDataRestorePolicy.self, forKey: .volumeDataRestorePolicy)
    self.clusterResourceConflictPolicy = try container.decode(
      RestoreConfig.ClusterResourceConflictPolicy.self, forKey: .clusterResourceConflictPolicy)
    self.namespacedResourceRestoreMode = try container.decode(
      RestoreConfig.NamespacedResourceRestoreMode.self, forKey: .namespacedResourceRestoreMode)
    self.clusterResourceRestoreScope = try container.decodeIfPresent(
      RestoreConfig.ClusterResourceRestoreScope.self, forKey: .clusterResourceRestoreScope)
    self.substitutionRules = try container.decode(
      [RestoreConfig.SubstitutionRule].self, forKey: .substitutionRules)
    self.transformationRules = try container.decode(
      [RestoreConfig.TransformationRule].self, forKey: .transformationRules)
    self.volumeDataRestorePolicyBindings = try container.decode(
      [RestoreConfig.VolumeDataRestorePolicyBinding].self, forKey: .volumeDataRestorePolicyBindings)
    self.restoreOrder = try container.decodeIfPresent(
      RestoreConfig.RestoreOrder.self, forKey: .restoreOrder)

    var namespacedResourceRestoreScope: OneOf_NamespacedResourceRestoreScope? = nil
    let namespacedResourceRestoreScopeCheckAndSet = {
      if namespacedResourceRestoreScope != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'namespacedResourceRestoreScope'"))
      }
      namespacedResourceRestoreScope = $0
    }
    if let allNamespaces = try container.decodeIfPresent(Swift.Bool.self, forKey: .allNamespaces) {
      try namespacedResourceRestoreScopeCheckAndSet(.allNamespaces(allNamespaces))
    }
    if let selectedNamespaces = try container.decodeIfPresent(
      Namespaces?.self, forKey: .selectedNamespaces)
    {
      try namespacedResourceRestoreScopeCheckAndSet(.selectedNamespaces(selectedNamespaces))
    }
    if let selectedApplications = try container.decodeIfPresent(
      NamespacedNames?.self, forKey: .selectedApplications)
    {
      try namespacedResourceRestoreScopeCheckAndSet(.selectedApplications(selectedApplications))
    }
    if let noNamespaces = try container.decodeIfPresent(Swift.Bool.self, forKey: .noNamespaces) {
      try namespacedResourceRestoreScopeCheckAndSet(.noNamespaces(noNamespaces))
    }
    if let excludedNamespaces = try container.decodeIfPresent(
      Namespaces?.self, forKey: .excludedNamespaces)
    {
      try namespacedResourceRestoreScopeCheckAndSet(.excludedNamespaces(excludedNamespaces))
    }
    self.namespacedResourceRestoreScope = namespacedResourceRestoreScope
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.volumeDataRestorePolicy, forKey: .volumeDataRestorePolicy)
    try container.encode(self.clusterResourceConflictPolicy, forKey: .clusterResourceConflictPolicy)
    try container.encode(self.namespacedResourceRestoreMode, forKey: .namespacedResourceRestoreMode)
    try container.encode(self.clusterResourceRestoreScope, forKey: .clusterResourceRestoreScope)
    try container.encode(self.substitutionRules, forKey: .substitutionRules)
    try container.encode(self.transformationRules, forKey: .transformationRules)
    try container.encode(
      self.volumeDataRestorePolicyBindings, forKey: .volumeDataRestorePolicyBindings)
    try container.encode(self.restoreOrder, forKey: .restoreOrder)

    if let choice = self.namespacedResourceRestoreScope {
      switch choice {
      case .allNamespaces(let value):
        try container.encode(value, forKey: .allNamespaces)
      case .selectedNamespaces(let value):
        try container.encode(value, forKey: .selectedNamespaces)
      case .selectedApplications(let value):
        try container.encode(value, forKey: .selectedApplications)
      case .noNamespaces(let value):
        try container.encode(value, forKey: .noNamespaces)
      case .excludedNamespaces(let value):
        try container.encode(value, forKey: .excludedNamespaces)
      }
    }
  }

  /// This is a direct map to the Kubernetes GroupKind type
  /// [GroupKind](https://godoc.org/k8s.io/apimachinery/pkg/runtime/schema#GroupKind)
  /// and is used for identifying specific "types" of resources to restore.
  public struct GroupKind: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. API group string of a Kubernetes resource, e.g.
    /// "apiextensions.k8s.io", "storage.k8s.io", etc.
    /// Note: use empty string for core API group.
    public var resourceGroup: Swift.String = Swift.String()

    /// Optional. Kind of a Kubernetes resource, must be in UpperCamelCase
    /// (PascalCase) and singular form. E.g. "CustomResourceDefinition",
    /// "StorageClass", etc.
    public var resourceKind: Swift.String = Swift.String()

    /// Initialize a new instance of `GroupKind`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GroupKind().with { $0.resourceGroup = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.GroupKind"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the scope of cluster-scoped resources to restore.
  ///
  /// Some group kinds are not reasonable choices for a restore, and will cause
  /// an error if selected here. Any scope selection that would restore
  /// "all valid" resources automatically excludes these group kinds.
  /// - Node
  /// - ComponentStatus
  /// - gkebackup.gke.io/BackupJob
  /// - gkebackup.gke.io/RestoreJob
  /// - metrics.k8s.io/NodeMetrics
  /// - migration.k8s.io/StorageState
  /// - migration.k8s.io/StorageVersionMigration
  /// - snapshot.storage.k8s.io/VolumeSnapshotContent
  /// - storage.k8s.io/CSINode
  /// - storage.k8s.io/VolumeAttachment
  ///
  /// Some group kinds are driven by restore configuration elsewhere,
  /// and will cause an error if selected here.
  /// - Namespace
  /// - PersistentVolume
  public struct ClusterResourceRestoreScope: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. A list of cluster-scoped resource group kinds to restore from
    /// the backup. If specified, only the selected resources will be restored.
    /// Mutually exclusive to any other field in the message.
    public var selectedGroupKinds: [RestoreConfig.GroupKind] = []

    /// Optional. A list of cluster-scoped resource group kinds to NOT restore
    /// from the backup. If specified, all valid cluster-scoped resources will be
    /// restored except for those specified in the list.
    /// Mutually exclusive to any other field in the message.
    public var excludedGroupKinds: [RestoreConfig.GroupKind] = []

    /// Optional. If True, all valid cluster-scoped resources will be restored.
    /// Mutually exclusive to any other field in the message.
    public var allGroupKinds: Swift.Bool = Swift.Bool()

    /// Optional. If True, no cluster-scoped resources will be restored.
    /// This has the same restore scope as if the message is not defined.
    /// Mutually exclusive to any other field in the message.
    public var noGroupKinds: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `ClusterResourceRestoreScope`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClusterResourceRestoreScope().with { $0.selectedGroupKinds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.ClusterResourceRestoreScope"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A transformation rule to be applied against Kubernetes resources as they
  /// are selected for restoration from a Backup. A rule contains both filtering
  /// logic (which resources are subject to substitution) and substitution logic.
  public struct SubstitutionRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. (Filtering parameter) Any resource subject to substitution must
    /// be contained within one of the listed Kubernetes Namespace in the Backup.
    /// If this field is not provided, no namespace filtering will be performed
    /// (all resources in all Namespaces, including all cluster-scoped resources,
    /// will be candidates for substitution).
    /// To mix cluster-scoped and namespaced resources in the same rule, use an
    /// empty string ("") as one of the target namespaces.
    public var targetNamespaces: [Swift.String] = []

    /// Optional. (Filtering parameter) Any resource subject to substitution must
    /// belong to one of the listed "types". If this field is not provided, no
    /// type filtering will be performed (all resources of all types matching
    /// previous filtering parameters will be candidates for substitution).
    public var targetGroupKinds: [RestoreConfig.GroupKind] = []

    /// Required. This is a [JSONPath]
    /// (https://kubernetes.io/docs/reference/kubectl/jsonpath/)
    /// expression that matches specific fields of candidate
    /// resources and it operates as both a filtering parameter (resources that
    /// are not matched with this expression will not be candidates for
    /// substitution) as well as a field identifier (identifies exactly which
    /// fields out of the candidate resources will be modified).
    public var targetJsonPath: Swift.String = Swift.String()

    /// Optional. (Filtering parameter) This is a [regular expression]
    /// (https://en.wikipedia.org/wiki/Regular_expression)
    /// that is compared against the fields matched by the target_json_path
    /// expression (and must also have passed the previous filters).
    /// Substitution will not be performed against fields whose
    /// value does not match this expression. If this field is NOT specified,
    /// then ALL fields matched by the target_json_path expression will undergo
    /// substitution. Note that an empty (e.g., "", rather than unspecified)
    /// value for this field will only match empty fields.
    public var originalValuePattern: Swift.String = Swift.String()

    /// Optional. This is the new value to set for any fields that pass the
    /// filtering and selection criteria. To remove a value from a Kubernetes
    /// resource, either leave this field unspecified, or set it to the empty
    /// string ("").
    public var newValue: Swift.String = Swift.String()

    /// Initialize a new instance of `SubstitutionRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubstitutionRule().with { $0.targetNamespaces = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.SubstitutionRule"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// TransformationRuleAction defines a TransformationRule action based on the
  /// JSON Patch RFC (https://www.rfc-editor.org/rfc/rfc6902)
  public struct TransformationRuleAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. op specifies the operation to perform.
    public var op: RestoreConfig.TransformationRuleAction.Op = RestoreConfig
      .TransformationRuleAction.Op()

    /// Optional. A string containing a JSON Pointer value that references the
    /// location in the target document to move the value from.
    public var fromPath: Swift.String = Swift.String()

    /// Optional. A string containing a JSON-Pointer value that references a
    /// location within the target document where the operation is performed.
    public var path: Swift.String = Swift.String()

    /// Optional. A string that specifies the desired value in string format to
    /// use for transformation.
    public var value: Swift.String = Swift.String()

    /// Initialize a new instance of `TransformationRuleAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TransformationRuleAction().with { $0.op = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Possible values for operations of a transformation rule action.
    public enum Op: Codable, Equatable, Sendable {
      /// Unspecified operation
      case unspecified
      /// The "remove" operation removes the value at the target location.
      case remove
      /// The "move" operation removes the value at a specified location and
      /// adds it to the target location.
      case move
      /// The "copy" operation copies the value at a specified location to the
      /// target location.
      case copy
      /// The "add" operation performs one of the following functions,
      /// depending upon what the target location references:
      /// 1. If the target location specifies an array index, a new value is
      /// inserted into the array at the specified index.
      /// 2. If the target location specifies an object member that does not
      /// already exist, a new member is added to the object.
      /// 3. If the target location specifies an object member that does exist,
      /// that member's value is replaced.
      case add
      /// The "test" operation tests that a value at the target location is
      /// equal to a specified value.
      case test
      /// The "replace" operation replaces the value at the target location
      /// with a new value.  The operation object MUST contain a "value" member
      /// whose content specifies the replacement value.
      case replace
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .remove: return 1
        case .move: return 2
        case .copy: return 3
        case .add: return 4
        case .test: return 5
        case .replace: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "OP_UNSPECIFIED"
        case .remove: return "REMOVE"
        case .move: return "MOVE"
        case .copy: return "COPY"
        case .add: return "ADD"
        case .test: return "TEST"
        case .replace: return "REPLACE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Op/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "OP_UNSPECIFIED": self = .unspecified
        case "REMOVE": self = .remove
        case "MOVE": self = .move
        case "COPY": self = .copy
        case "ADD": self = .add
        case "TEST": self = .test
        case "REPLACE": self = .replace
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Op/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .remove
        case 2: self = .move
        case 3: self = .copy
        case 4: self = .add
        case 5: self = .test
        case 6: self = .replace
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .remove: return try container.encode(1)
        case .move: return try container.encode(2)
        case .copy: return try container.encode(3)
        case .add: return try container.encode(4)
        case .test: return try container.encode(5)
        case .replace: return try container.encode(6)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.TransformationRuleAction"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// ResourceFilter specifies matching criteria to limit the scope of a
  /// change to a specific set of kubernetes resources that are selected for
  /// restoration from a backup.
  public struct ResourceFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. (Filtering parameter) Any resource subject to transformation
    /// must be contained within one of the listed Kubernetes Namespace in the
    /// Backup. If this field is not provided, no namespace filtering will be
    /// performed (all resources in all Namespaces, including all cluster-scoped
    /// resources, will be candidates for transformation).
    public var namespaces: [Swift.String] = []

    /// Optional. (Filtering parameter) Any resource subject to transformation
    /// must belong to one of the listed "types". If this field is not provided,
    /// no type filtering will be performed (all resources of all types matching
    /// previous filtering parameters will be candidates for transformation).
    public var groupKinds: [RestoreConfig.GroupKind] = []

    /// Optional. This is a [JSONPath]
    /// (https://github.com/json-path/JsonPath/blob/master/README.md)
    /// expression that matches specific fields of candidate
    /// resources and it operates as a filtering parameter (resources that
    /// are not matched with this expression will not be candidates for
    /// transformation).
    public var jsonPath: Swift.String = Swift.String()

    /// Initialize a new instance of `ResourceFilter`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceFilter().with { $0.namespaces = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.ResourceFilter"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A transformation rule to be applied against Kubernetes resources as they
  /// are selected for restoration from a Backup. A rule contains both filtering
  /// logic (which resources are subject to transform) and transformation logic.
  public struct TransformationRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. A list of transformation rule actions to take against candidate
    /// resources. Actions are executed in order defined - this order matters, as
    /// they could potentially interfere with each other and the first operation
    /// could affect the outcome of the second operation.
    public var fieldActions: [RestoreConfig.TransformationRuleAction] = []

    /// Optional. This field is used to specify a set of fields that should be
    /// used to determine which resources in backup should be acted upon by the
    /// supplied transformation rule actions, and this will ensure that only
    /// specific resources are affected by transformation rule actions.
    public var resourceFilter: RestoreConfig.ResourceFilter? = nil

    /// Optional. The description is a user specified string description of the
    /// transformation rule.
    public var description: Swift.String = Swift.String()

    /// Initialize a new instance of `TransformationRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TransformationRule().with { $0.fieldActions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.TransformationRule"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Binds resources in the scope to the given VolumeDataRestorePolicy.
  public struct VolumeDataRestorePolicyBinding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The VolumeDataRestorePolicy to apply when restoring volumes in
    /// scope.
    public var policy: RestoreConfig.VolumeDataRestorePolicy =
      RestoreConfig.VolumeDataRestorePolicy()

    public var scope: OneOf_Scope? = nil

    /// Initialize a new instance of `VolumeDataRestorePolicyBinding`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VolumeDataRestorePolicyBinding().with { $0.policy = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case policy = "policy"
      case volumeType = "volumeType"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.policy = try container.decode(
        RestoreConfig.VolumeDataRestorePolicy.self, forKey: .policy)

      var scope: OneOf_Scope? = nil
      let scopeCheckAndSet = {
        if scope != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'scope'"))
        }
        scope = $0
      }
      if let volumeType = try container.decodeIfPresent(
        VolumeTypeEnum.VolumeType.self, forKey: .volumeType)
      {
        try scopeCheckAndSet(.volumeType(volumeType))
      }
      self.scope = scope
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.policy, forKey: .policy)

      if let choice = self.scope {
        switch choice {
        case .volumeType(let value):
          try container.encode(value, forKey: .volumeType)
        }
      }
    }

    public enum OneOf_Scope: Codable, Equatable, Sendable {
      /// The volume type, as determined by the PVC's bound PV,
      /// to apply the policy to.
      case volumeType(VolumeTypeEnum.VolumeType)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.VolumeDataRestorePolicyBinding"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Allows customers to specify dependencies between resources
  /// that Backup for GKE can use to compute a resasonable restore order.
  public struct RestoreOrder: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Contains a list of group kind dependency pairs provided
    /// by the customer, that is used by Backup for GKE to
    /// generate a group kind restore order.
    public var groupKindDependencies: [RestoreConfig.RestoreOrder.GroupKindDependency] = []

    /// Initialize a new instance of `RestoreOrder`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RestoreOrder().with { $0.groupKindDependencies = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Defines a dependency between two group kinds.
    public struct GroupKindDependency: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. The satisfying group kind must be restored first
      /// in order to satisfy the dependency.
      public var satisfying: RestoreConfig.GroupKind? = nil

      /// Required. The requiring group kind requires that the other
      /// group kind be restored first.
      public var requiring: RestoreConfig.GroupKind? = nil

      /// Initialize a new instance of `GroupKindDependency`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GroupKindDependency().with { $0.satisfying = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.RestoreOrder.GroupKindDependency"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig.RestoreOrder"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines how volume data should be restored.
  public enum VolumeDataRestorePolicy: Codable, Equatable, Sendable {
    /// Unspecified (illegal).
    case unspecified
    /// For each PVC to be restored, create a new underlying volume and PV
    /// from the corresponding VolumeBackup contained within the Backup.
    case restoreVolumeDataFromBackup
    /// For each PVC to be restored, attempt to reuse the original PV contained
    /// in the Backup (with its original underlying volume). This option
    /// is likely only usable when restoring a workload to its original cluster.
    case reuseVolumeHandleFromBackup
    /// For each PVC to be restored, create PVC without any particular
    /// action to restore data. In this case, the normal Kubernetes provisioning
    /// logic would kick in, and this would likely result in either dynamically
    /// provisioning blank PVs or binding to statically provisioned PVs.
    case noVolumeDataRestoration
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .restoreVolumeDataFromBackup: return 1
      case .reuseVolumeHandleFromBackup: return 2
      case .noVolumeDataRestoration: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VOLUME_DATA_RESTORE_POLICY_UNSPECIFIED"
      case .restoreVolumeDataFromBackup: return "RESTORE_VOLUME_DATA_FROM_BACKUP"
      case .reuseVolumeHandleFromBackup: return "REUSE_VOLUME_HANDLE_FROM_BACKUP"
      case .noVolumeDataRestoration: return "NO_VOLUME_DATA_RESTORATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VolumeDataRestorePolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VOLUME_DATA_RESTORE_POLICY_UNSPECIFIED": self = .unspecified
      case "RESTORE_VOLUME_DATA_FROM_BACKUP": self = .restoreVolumeDataFromBackup
      case "REUSE_VOLUME_HANDLE_FROM_BACKUP": self = .reuseVolumeHandleFromBackup
      case "NO_VOLUME_DATA_RESTORATION": self = .noVolumeDataRestoration
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VolumeDataRestorePolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .restoreVolumeDataFromBackup
      case 2: self = .reuseVolumeHandleFromBackup
      case 3: self = .noVolumeDataRestoration
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .restoreVolumeDataFromBackup: return try container.encode(1)
      case .reuseVolumeHandleFromBackup: return try container.encode(2)
      case .noVolumeDataRestoration: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines the behavior for handling the situation where cluster-scoped
  /// resources being restored already exist in the target cluster.
  public enum ClusterResourceConflictPolicy: Codable, Equatable, Sendable {
    /// Unspecified. Only allowed if no cluster-scoped resources will be
    /// restored.
    case unspecified
    /// Do not attempt to restore the conflicting resource.
    case useExistingVersion
    /// Delete the existing version before re-creating it from the Backup.
    /// This is a dangerous option which could cause unintentional
    /// data loss if used inappropriately. For example, deleting a CRD will
    /// cause Kubernetes to delete all CRs of that type.
    case useBackupVersion
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .useExistingVersion: return 1
      case .useBackupVersion: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLUSTER_RESOURCE_CONFLICT_POLICY_UNSPECIFIED"
      case .useExistingVersion: return "USE_EXISTING_VERSION"
      case .useBackupVersion: return "USE_BACKUP_VERSION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ClusterResourceConflictPolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLUSTER_RESOURCE_CONFLICT_POLICY_UNSPECIFIED": self = .unspecified
      case "USE_EXISTING_VERSION": self = .useExistingVersion
      case "USE_BACKUP_VERSION": self = .useBackupVersion
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ClusterResourceConflictPolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .useExistingVersion
      case 2: self = .useBackupVersion
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .useExistingVersion: return try container.encode(1)
      case .useBackupVersion: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines the behavior for handling the situation where sets of namespaced
  /// resources being restored already exist in the target cluster.
  public enum NamespacedResourceRestoreMode: Codable, Equatable, Sendable {
    /// Unspecified (invalid).
    case unspecified
    /// When conflicting top-level resources (either Namespaces or
    /// ProtectedApplications, depending upon the scope) are encountered, this
    /// will first trigger a delete of the conflicting resource AND ALL OF ITS
    /// REFERENCED RESOURCES (e.g., all resources in the Namespace or all
    /// resources referenced by the ProtectedApplication) before restoring the
    /// resources from the Backup. This mode should only be used when you are
    /// intending to revert some portion of a cluster to an earlier state.
    case deleteAndRestore
    /// If conflicting top-level resources (either Namespaces or
    /// ProtectedApplications, depending upon the scope) are encountered at the
    /// beginning of a restore process, the Restore will fail.  If a conflict
    /// occurs during the restore process itself (e.g., because an out of band
    /// process creates conflicting resources), a conflict will be reported.
    case failOnConflict
    /// This mode merges the backup and the target cluster and skips the
    /// conflicting resources. If a single resource to restore exists in the
    /// cluster before restoration, the resource will be skipped, otherwise it
    /// will be restored.
    case mergeSkipOnConflict
    /// This mode merges the backup and the target cluster and skips the
    /// conflicting resources except volume data. If a PVC to restore already
    /// exists, this mode will restore/reconnect the volume without overwriting
    /// the PVC. It is similar to MERGE_SKIP_ON_CONFLICT except that it will
    /// apply the volume data policy for the conflicting PVCs:
    /// - RESTORE_VOLUME_DATA_FROM_BACKUP: restore data only and respect the
    ///   reclaim policy of the original PV;
    /// - REUSE_VOLUME_HANDLE_FROM_BACKUP: reconnect and respect the reclaim
    ///   policy of the original PV;
    /// - NO_VOLUME_DATA_RESTORATION: new provision and respect the reclaim
    ///   policy of the original PV.
    /// Note that this mode could cause data loss as the original PV can be
    /// retained or deleted depending on its reclaim policy.
    case mergeReplaceVolumeOnConflict
    /// This mode merges the backup and the target cluster and replaces the
    /// conflicting resources with the ones in the backup. If a single resource
    /// to restore exists in the cluster before restoration, the resource will be
    /// replaced with the one from the backup. To replace an existing resource,
    /// the first attempt is to update the resource to match the one from the
    /// backup; if the update fails, the second attempt is to delete the resource
    /// and restore it from the backup.
    /// Note that this mode could cause data loss as it replaces the existing
    /// resources in the target cluster, and the original PV can be retained or
    /// deleted depending on its reclaim policy.
    case mergeReplaceOnConflict
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .deleteAndRestore: return 1
      case .failOnConflict: return 2
      case .mergeSkipOnConflict: return 3
      case .mergeReplaceVolumeOnConflict: return 4
      case .mergeReplaceOnConflict: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "NAMESPACED_RESOURCE_RESTORE_MODE_UNSPECIFIED"
      case .deleteAndRestore: return "DELETE_AND_RESTORE"
      case .failOnConflict: return "FAIL_ON_CONFLICT"
      case .mergeSkipOnConflict: return "MERGE_SKIP_ON_CONFLICT"
      case .mergeReplaceVolumeOnConflict: return "MERGE_REPLACE_VOLUME_ON_CONFLICT"
      case .mergeReplaceOnConflict: return "MERGE_REPLACE_ON_CONFLICT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NamespacedResourceRestoreMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NAMESPACED_RESOURCE_RESTORE_MODE_UNSPECIFIED": self = .unspecified
      case "DELETE_AND_RESTORE": self = .deleteAndRestore
      case "FAIL_ON_CONFLICT": self = .failOnConflict
      case "MERGE_SKIP_ON_CONFLICT": self = .mergeSkipOnConflict
      case "MERGE_REPLACE_VOLUME_ON_CONFLICT": self = .mergeReplaceVolumeOnConflict
      case "MERGE_REPLACE_ON_CONFLICT": self = .mergeReplaceOnConflict
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NamespacedResourceRestoreMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .deleteAndRestore
      case 2: self = .failOnConflict
      case 3: self = .mergeSkipOnConflict
      case 4: self = .mergeReplaceVolumeOnConflict
      case 5: self = .mergeReplaceOnConflict
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .deleteAndRestore: return try container.encode(1)
      case .failOnConflict: return try container.encode(2)
      case .mergeSkipOnConflict: return try container.encode(3)
      case .mergeReplaceVolumeOnConflict: return try container.encode(4)
      case .mergeReplaceOnConflict: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies the namespaced resources to restore from the Backup.
  /// Only one of the entries may be specified. If not specified, NO namespaced
  /// resources will be restored.
  ///
  /// Note: Resources will never be restored into *managed* namespaces such as
  /// `kube-system`, `kube-public`, or `kube-node-lease`. These namespaces
  /// are silently skipped when
  /// [all_namespaces][google.cloud.gkebackup.v1.RestoreConfig.all_namespaces] is
  /// selected. Listing them explicitly will result in an error.
  ///
  /// [google.cloud.gkebackup.v1.RestoreConfig.all_namespaces]: <doc:RestoreConfig/allNamespaces>
  public enum OneOf_NamespacedResourceRestoreScope: Codable, Equatable, Sendable {
    /// Restore all namespaced resources in the Backup if set to "True".
    /// Specifying this field to "False" is an error.
    case allNamespaces(Swift.Bool)
    /// A list of selected Namespaces to restore from the Backup. The listed
    /// Namespaces and all resources contained in them will be restored.
    indirect case selectedNamespaces(Namespaces?)
    /// A list of selected ProtectedApplications to restore. The listed
    /// ProtectedApplications and all the resources to which they refer will be
    /// restored.
    indirect case selectedApplications(NamespacedNames?)
    /// Do not restore any namespaced resources if set to "True".
    /// Specifying this field to "False" is not allowed.
    case noNamespaces(Swift.Bool)
    /// A list of selected namespaces excluded from restoration. All
    /// namespaces except those in this list will be restored.
    indirect case excludedNamespaces(Namespaces?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.RestoreConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
