// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents both a request to Restore some portion of a Backup into
/// a target GKE cluster and a record of the restore operation itself.
public struct Restore: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full name of the Restore resource.
  /// Format: `projects/*/locations/*/restorePlans/*/restores/*`
  public var name: Swift.String = Swift.String()

  /// Output only. Server generated global unique identifier of
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) format.
  public var uid: Swift.String = Swift.String()

  /// Output only. The timestamp when this Restore resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when this Restore resource was last
  /// updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. User specified descriptive string for this Restore.
  public var description: Swift.String = Swift.String()

  /// Required. Immutable. A reference to the
  /// [Backup][google.cloud.gkebackup.v1.Backup] used as the source from which
  /// this Restore will restore. Note that this Backup must be a sub-resource of
  /// the RestorePlan's
  /// [backup_plan][google.cloud.gkebackup.v1.RestorePlan.backup_plan]. Format:
  /// `projects/*/locations/*/backupPlans/*/backups/*`.
  ///
  /// [google.cloud.gkebackup.v1.Backup]: <doc:Backup>
  /// [google.cloud.gkebackup.v1.RestorePlan.backup_plan]: <doc:RestorePlan/backupPlan>
  public var backup: Swift.String = Swift.String()

  /// Output only. The target cluster into which this Restore will restore data.
  /// Valid formats:
  ///
  ///   - `projects/*/locations/*/clusters/*`
  ///   - `projects/*/zones/*/clusters/*`
  ///
  /// Inherited from parent RestorePlan's
  /// [cluster][google.cloud.gkebackup.v1.RestorePlan.cluster] value.
  ///
  /// [google.cloud.gkebackup.v1.RestorePlan.cluster]: <doc:RestorePlan/cluster>
  public var cluster: Swift.String = Swift.String()

  /// Output only. Configuration of the Restore.  Inherited from parent
  /// RestorePlan's
  /// [restore_config][google.cloud.gkebackup.v1.RestorePlan.restore_config].
  ///
  /// [google.cloud.gkebackup.v1.RestorePlan.restore_config]: <doc:RestorePlan/restoreConfig>
  public var restoreConfig: RestoreConfig? = nil

  /// A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The current state of the Restore.
  public var state: Restore.State = Restore.State()

  /// Output only. Human-readable description of why the Restore is in its
  /// current state. This field is only meant for human readability and should
  /// not be used programmatically as this field is not guaranteed to be
  /// consistent.
  public var stateReason: Swift.String = Swift.String()

  /// Output only. Timestamp of when the restore operation completed.
  public var completeTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Number of resources restored during the restore execution.
  public var resourcesRestoredCount: Swift.Int32 = Swift.Int32()

  /// Output only. Number of resources excluded during the restore execution.
  public var resourcesExcludedCount: Swift.Int32 = Swift.Int32()

  /// Output only. Number of resources that failed to be restored during the
  /// restore execution.
  public var resourcesFailedCount: Swift.Int32 = Swift.Int32()

  /// Output only. Number of volumes restored during the restore execution.
  public var volumesRestoredCount: Swift.Int32 = Swift.Int32()

  /// Output only. `etag` is used for optimistic concurrency control as a way to
  /// help prevent simultaneous updates of a restore from overwriting each other.
  /// It is strongly suggested that systems make use of the `etag` in the
  /// read-modify-write cycle to perform restore updates in order to avoid
  /// race conditions: An `etag` is returned in the response to `GetRestore`,
  /// and systems are expected to put that etag in the request to
  /// `UpdateRestore` or `DeleteRestore` to ensure that their change will be
  /// applied to the same version of the resource.
  public var etag: Swift.String = Swift.String()

  /// Optional. Immutable. Filters resources for `Restore`. If not specified, the
  /// scope of the restore will remain the same as defined in the `RestorePlan`.
  /// If this is specified and no resources are matched by the
  /// `inclusion_filters` or everything is excluded by the `exclusion_filters`,
  /// nothing will be restored. This filter can only be specified if the value of
  /// [namespaced_resource_restore_mode][google.cloud.gkebackup.v1.RestoreConfig.namespaced_resource_restore_mode]
  /// is set to `MERGE_SKIP_ON_CONFLICT`, `MERGE_REPLACE_VOLUME_ON_CONFLICT` or
  /// `MERGE_REPLACE_ON_CONFLICT`.
  ///
  /// [google.cloud.gkebackup.v1.RestoreConfig.namespaced_resource_restore_mode]: <doc:RestoreConfig/namespacedResourceRestoreMode>
  public var filter: Restore.Filter? = nil

  /// Optional. Immutable. Overrides the volume data restore policies selected in
  /// the Restore Config for override-scoped resources.
  public var volumeDataRestorePolicyOverrides: [VolumeDataRestorePolicyOverride] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Restore`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Restore().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let description = CodingKeys(stringValue: "description")
    static let backup = CodingKeys(stringValue: "backup")
    static let cluster = CodingKeys(stringValue: "cluster")
    static let restoreConfig = CodingKeys(stringValue: "restoreConfig")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let stateReason = CodingKeys(stringValue: "stateReason")
    static let completeTime = CodingKeys(stringValue: "completeTime")
    static let resourcesRestoredCount = CodingKeys(stringValue: "resourcesRestoredCount")
    static let resourcesExcludedCount = CodingKeys(stringValue: "resourcesExcludedCount")
    static let resourcesFailedCount = CodingKeys(stringValue: "resourcesFailedCount")
    static let volumesRestoredCount = CodingKeys(stringValue: "volumesRestoredCount")
    static let etag = CodingKeys(stringValue: "etag")
    static let filter = CodingKeys(stringValue: "filter")
    static let volumeDataRestorePolicyOverrides = CodingKeys(
      stringValue: "volumeDataRestorePolicyOverrides")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "createTime",
      "updateTime",
      "description",
      "backup",
      "cluster",
      "restoreConfig",
      "labels",
      "state",
      "stateReason",
      "completeTime",
      "resourcesRestoredCount",
      "resourcesExcludedCount",
      "resourcesFailedCount",
      "volumesRestoredCount",
      "etag",
      "filter",
      "volumeDataRestorePolicyOverrides",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backup) {
      self.backup = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
      self.cluster = value
    }
    self.restoreConfig = try container.decodeIfPresent(RestoreConfig.self, forKey: .restoreConfig)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Restore.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateReason) {
      self.stateReason = value
    }
    self.completeTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .completeTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .resourcesRestoredCount)
    {
      self.resourcesRestoredCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .resourcesExcludedCount)
    {
      self.resourcesExcludedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .resourcesFailedCount) {
      self.resourcesFailedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .volumesRestoredCount) {
      self.volumesRestoredCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    self.filter = try container.decodeIfPresent(Restore.Filter.self, forKey: .filter)
    if let value = try container.decodeIfPresent(
      [VolumeDataRestorePolicyOverride].self, forKey: .volumeDataRestorePolicyOverrides)
    {
      self.volumeDataRestorePolicyOverrides = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.backup, forKey: .backup)
    try container.encode(self.cluster, forKey: .cluster)
    try container.encodeIfPresent(self.restoreConfig, forKey: .restoreConfig)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateReason, forKey: .stateReason)
    try container.encodeIfPresent(self.completeTime, forKey: .completeTime)
    try container.encode(self.resourcesRestoredCount, forKey: .resourcesRestoredCount)
    try container.encode(self.resourcesExcludedCount, forKey: .resourcesExcludedCount)
    try container.encode(self.resourcesFailedCount, forKey: .resourcesFailedCount)
    try container.encode(self.volumesRestoredCount, forKey: .volumesRestoredCount)
    try container.encode(self.etag, forKey: .etag)
    try container.encodeIfPresent(self.filter, forKey: .filter)
    try container.encode(
      self.volumeDataRestorePolicyOverrides, forKey: .volumeDataRestorePolicyOverrides)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Defines the filter for `Restore`. This filter can be used to further
  /// refine the resource selection of the `Restore` beyond the coarse-grained
  /// scope defined in the `RestorePlan`. `exclusion_filters` take precedence
  /// over `inclusion_filters`. If a resource matches both `inclusion_filters`
  /// and `exclusion_filters`, it will not be restored.
  public struct Filter: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Selects resources for restoration. If specified, only resources
    /// which match `inclusion_filters` will be selected for restoration. A
    /// resource will be selected if it matches any `ResourceSelector` of the
    /// `inclusion_filters`.
    public var inclusionFilters: [ResourceSelector] = []

    /// Optional. Excludes resources from restoration. If specified,
    /// a resource will not be restored if it matches
    /// any `ResourceSelector` of the `exclusion_filters`.
    public var exclusionFilters: [ResourceSelector] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Filter`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Filter().with { $0.inclusionFilters = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inclusionFilters = CodingKeys(stringValue: "inclusionFilters")
      static let exclusionFilters = CodingKeys(stringValue: "exclusionFilters")

      static let _knownKeys: Set<Swift.String> = [
        "inclusionFilters",
        "exclusionFilters",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [ResourceSelector].self, forKey: .inclusionFilters)
      {
        self.inclusionFilters = value
      }
      if let value = try container.decodeIfPresent(
        [ResourceSelector].self, forKey: .exclusionFilters)
      {
        self.exclusionFilters = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.inclusionFilters, forKey: .inclusionFilters)
      try container.encode(self.exclusionFilters, forKey: .exclusionFilters)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.v1.Restore.Filter"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible values for state of the Restore.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The Restore resource is in the process of being created.
    case unspecified
    /// The Restore resource has been created and the associated RestoreJob
    /// Kubernetes resource has been injected into target cluster.
    case creating
    /// The gkebackup agent in the cluster has begun executing the restore
    /// operation.
    case inProgress
    /// The restore operation has completed successfully. Restored workloads may
    /// not yet be operational.
    case succeeded
    /// The restore operation has failed.
    case failed
    /// This Restore resource is in the process of being deleted.
    case deleting
    /// The Kubernetes resources created by this Restore are being
    /// validated.
    case validating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .inProgress: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .deleting: return 5
      case .validating: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .inProgress: return "IN_PROGRESS"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .validating: return "VALIDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "IN_PROGRESS": self = .inProgress
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      case "VALIDATING": self = .validating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .inProgress
      case 3: self = .succeeded
      case 4: self = .failed
      case 5: self = .deleting
      case 6: self = .validating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .deleting: return try container.encode("DELETING")
      case .validating: return try container.encode("VALIDATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.Restore"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
