// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Defines RPO scheduling configuration for automatically creating
/// Backups via this BackupPlan.
public struct RpoConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Defines the target RPO for the BackupPlan in minutes, which means
  /// the target maximum data loss in time that is acceptable for this
  /// BackupPlan. This must be at least 60, i.e., 1 hour, and at most 86400,
  /// i.e., 60 days.
  public var targetRpoMinutes: Swift.Int32 = Swift.Int32()

  /// Optional. User specified time windows during which backup can NOT happen
  /// for this BackupPlan - backups should start and finish outside of any given
  /// exclusion window. Note: backup jobs will be scheduled to start and
  /// finish outside the duration of the window as much as possible, but
  /// running jobs will not get canceled when it runs into the window.
  /// All the time and date values in exclusion_windows entry in the API are in
  /// UTC.
  /// We only allow <=1 recurrence (daily or weekly) exclusion window for a
  /// BackupPlan while no restriction on number of single occurrence
  /// windows.
  public var exclusionWindows: [ExclusionWindow] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RpoConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RpoConfig().with { $0.targetRpoMinutes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let targetRpoMinutes = CodingKeys(stringValue: "targetRpoMinutes")
    static let exclusionWindows = CodingKeys(stringValue: "exclusionWindows")

    static let _knownKeys: Set<Swift.String> = [
      "targetRpoMinutes",
      "exclusionWindows",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .targetRpoMinutes) {
      self.targetRpoMinutes = value
    }
    if let value = try container.decodeIfPresent([ExclusionWindow].self, forKey: .exclusionWindows)
    {
      self.exclusionWindows = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.targetRpoMinutes, forKey: .targetRpoMinutes)
    try container.encode(self.exclusionWindows, forKey: .exclusionWindows)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.RpoConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
