// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for UpdateBackupChannel.
public struct UpdateBackupChannelRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. A new version of the BackupChannel resource that contains updated
  /// fields. This may be sparsely populated if an `update_mask` is provided.
  public var backupChannel: BackupChannel? = nil

  /// Optional. This is used to specify the fields to be overwritten in the
  /// BackupChannel targeted for update. The values for each of these
  /// updated fields will be taken from the `backup_channel` provided
  /// with this request. Field names are relative to the root of the resource
  /// (e.g., `description`, `labels`, etc.)
  /// If no `update_mask` is provided, all fields in `backup_channel` will
  /// be written to the target BackupChannel resource. Note that
  /// OUTPUT_ONLY and IMMUTABLE fields in `backup_channel` are ignored and
  /// are not used to update the target BackupChannel.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateBackupChannelRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateBackupChannelRequest().with { $0.backupChannel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.UpdateBackupChannelRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
