// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for UpdateRestoreChannel.
public struct UpdateRestoreChannelRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. A new version of the RestoreChannel resource that contains
  /// updated fields. This may be sparsely populated if an `update_mask` is
  /// provided.
  public var restoreChannel: RestoreChannel? = nil

  /// Optional. This is used to specify the fields to be overwritten in the
  /// RestoreChannel targeted for update. The values for each of these
  /// updated fields will be taken from the `restore_channel` provided
  /// with this request. Field names are relative to the root of the resource
  /// (e.g., `description`, `destination_project_id`, etc.)
  /// If no `update_mask` is provided, all fields in `restore_channel` will
  /// be written to the target RestoreChannel resource. Note that
  /// OUTPUT_ONLY and IMMUTABLE fields in `restore_channel` are ignored and
  /// are not used to update the target RestoreChannel.
  public var updateMask: GoogleWKT.FieldMask? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateRestoreChannelRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateRestoreChannelRequest().with { $0.restoreChannel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let restoreChannel = CodingKeys(stringValue: "restoreChannel")
    static let updateMask = CodingKeys(stringValue: "updateMask")

    static let _knownKeys: Set<Swift.String> = [
      "restoreChannel",
      "updateMask",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.restoreChannel = try container.decodeIfPresent(
      RestoreChannel.self, forKey: .restoreChannel)
    self.updateMask = try container.decodeIfPresent(GoogleWKT.FieldMask.self, forKey: .updateMask)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.restoreChannel, forKey: .restoreChannel)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.v1.UpdateRestoreChannelRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
